// 自动生成：src/side_panel/emoji-data.js
// 全量 emoji 数据（Unicode 15.1 RGI 集合），条目格式：[emoji字符, 英文名, 分类, 中文关键词]
// 分类: smileys表情 / people人物 / animals动物 / food食物 / travel交通 / activity活动 / objects物品 / symbols符号 / flags旗帜
export const EMOJI_DATA = [
  ['🀄', 'mahjong tile red dragon', 'symbols', '麻将,红中'],
  ['🃏', 'playing card black joker', 'symbols', ''],
  ['🅰', 'negative squared latin capital letter a', 'symbols', ''],
  ['🅱', 'negative squared latin capital letter b', 'symbols', ''],
  ['🅾', 'negative squared latin capital letter o', 'symbols', ''],
  ['🅿', 'negative squared latin capital letter p', 'symbols', ''],
  ['🆎', 'negative squared ab', 'symbols', ''],
  ['🆑', 'squared cl', 'symbols', ''],
  ['🆒', 'squared cool', 'symbols', ''],
  ['🆓', 'squared free', 'symbols', ''],
  ['🆔', 'squared id', 'symbols', ''],
  ['🆕', 'squared new', 'symbols', ''],
  ['🆖', 'squared ng', 'symbols', ''],
  ['🆗', 'squared ok', 'symbols', ''],
  ['🆘', 'squared sos', 'symbols', ''],
  ['🆙', 'squared up with exclamation mark', 'symbols', ''],
  ['🆚', 'squared vs', 'symbols', ''],
  ['🇨🇩', 'regional indicator symbol letter c', 'flags', ''],
  ['🇬🇭', 'regional indicator symbol letter g', 'flags', ''],
  ['🇲🇳', 'regional indicator symbol letter m', 'flags', ''],
  ['🇷🇸', 'regional indicator symbol letter r', 'flags', ''],
  ['🈁', 'squared katakana koko', 'symbols', ''],
  ['🈂', 'squared katakana sa', 'symbols', ''],
  ['🈚', 'squared cjk unified ideograph-7121', 'symbols', ''],
  ['🈯', 'squared cjk unified ideograph-6307', 'symbols', ''],
  ['🈲', 'squared cjk unified ideograph-7981', 'symbols', ''],
  ['🈳', 'squared cjk unified ideograph-7a7a', 'symbols', ''],
  ['🈴', 'squared cjk unified ideograph-5408', 'symbols', ''],
  ['🈵', 'squared cjk unified ideograph-6e80', 'symbols', ''],
  ['🈶', 'squared cjk unified ideograph-6709', 'symbols', ''],
  ['🈷', 'squared cjk unified ideograph-6708', 'symbols', ''],
  ['🈸', 'squared cjk unified ideograph-7533', 'symbols', ''],
  ['🈹', 'squared cjk unified ideograph-5272', 'symbols', ''],
  ['🈺', 'squared cjk unified ideograph-55b6', 'symbols', ''],
  ['🉐', 'circled ideograph advantage', 'symbols', ''],
  ['🉑', 'circled ideograph accept', 'symbols', ''],
  ['🌀', 'cyclone', 'symbols', '台风,龙卷风,旋风'],
  ['🌁', 'foggy', 'symbols', '雾,雾霾,朦胧'],
  ['🌂', 'closed umbrella', 'symbols', ''],
  ['🌃', 'night with stars', 'symbols', '夜晚,星空,城市'],
  ['🌄', 'sunrise over mountains', 'symbols', '日出,山,早晨'],
  ['🌅', 'sunrise', 'symbols', '日出,太阳,早晨'],
  ['🌆', 'cityscape at dusk', 'symbols', '黄昏,傍晚,城市'],
  ['🌇', 'sunset over buildings', 'symbols', '日落,黄昏'],
  ['🌈', 'rainbow', 'symbols', '彩虹,雨后'],
  ['🌉', 'bridge at night', 'symbols', '桥,大桥'],
  ['🌊', 'water wave', 'symbols', '海浪,波浪,海'],
  ['🌋', 'volcano', 'symbols', '火山,爆发'],
  ['🌌', 'milky way', 'symbols', ''],
  ['🌍', 'earth globe europe-africa', 'symbols', ''],
  ['🌎', 'earth globe americas', 'symbols', '地球,美洲'],
  ['🌏', 'earth globe asia-australia', 'symbols', '地球,亚洲'],
  ['🌐', 'globe with meridians', 'symbols', ''],
  ['🌑', 'new moon symbol', 'symbols', ''],
  ['🌒', 'waxing crescent moon symbol', 'symbols', ''],
  ['🌓', 'first quarter moon symbol', 'symbols', ''],
  ['🌔', 'waxing gibbous moon symbol', 'symbols', ''],
  ['🌕', 'full moon symbol', 'symbols', ''],
  ['🌖', 'waning gibbous moon symbol', 'symbols', ''],
  ['🌗', 'last quarter moon symbol', 'symbols', ''],
  ['🌘', 'waning crescent moon symbol', 'symbols', ''],
  ['🌙', 'crescent moon', 'symbols', ''],
  ['🌚', 'new moon with face', 'symbols', ''],
  ['🌛', 'first quarter moon with face', 'symbols', ''],
  ['🌜', 'last quarter moon with face', 'symbols', ''],
  ['🌝', 'full moon with face', 'symbols', ''],
  ['🌞', 'sun with face', 'symbols', ''],
  ['🌟', 'glowing star', 'symbols', '星星,闪光,闪耀'],
  ['🌠', 'shooting star', 'symbols', ''],
  ['🌡', 'thermometer', 'symbols', ''],
  ['🌤', 'white sun with small cloud', 'symbols', ''],
  ['🌥', 'white sun behind cloud', 'symbols', ''],
  ['🌦', 'white sun behind cloud with rain', 'symbols', ''],
  ['🌧', 'cloud with rain', 'symbols', ''],
  ['🌨', 'cloud with snow', 'symbols', ''],
  ['🌩', 'cloud with lightning', 'symbols', ''],
  ['🌪', 'cloud with tornado', 'symbols', ''],
  ['🌫', 'fog', 'symbols', ''],
  ['🌬', 'wind blowing face', 'symbols', ''],
  ['🌭', 'hot dog', 'food', '热狗'],
  ['🌮', 'taco', 'food', '墨西哥卷饼'],
  ['🌯', 'burrito', 'food', '墨西哥卷,卷饼'],
  ['🌰', 'chestnut', 'food', '栗子,坚果'],
  ['🌱', 'seedling', 'food', ''],
  ['🌲', 'evergreen tree', 'food', '松树,树'],
  ['🌳', 'deciduous tree', 'food', '树,大树'],
  ['🌴', 'palm tree', 'food', '棕榈树,热带,度假'],
  ['🌵', 'cactus', 'food', '仙人掌,沙漠'],
  ['🌶', 'hot pepper', 'food', ''],
  ['🌷', 'tulip', 'food', '郁金香,花'],
  ['🌸', 'cherry blossom', 'food', '樱花,花,春天'],
  ['🌹', 'rose', 'food', '玫瑰,花,爱情'],
  ['🌺', 'hibiscus', 'food', '花,芙蓉'],
  ['🌻', 'sunflower', 'food', '向日葵,花,太阳'],
  ['🌼', 'blossom', 'food', '雏菊,花'],
  ['🌽', 'ear of maize', 'food', '玉米'],
  ['🌾', 'ear of rice', 'food', ''],
  ['🌿', 'herb', 'food', '草,植物,草药'],
  ['🍀', 'four leaf clover', 'food', '四叶草,幸运,好运'],
  ['🍁', 'maple leaf', 'food', '枫叶,秋天,红叶'],
  ['🍂', 'fallen leaf', 'food', '落叶,秋天'],
  ['🍃', 'leaf fluttering in wind', 'food', '树叶,风'],
  ['🍄', 'mushroom', 'food', '蘑菇,菌'],
  ['🍅', 'tomato', 'food', '番茄,西红柿'],
  ['🍆', 'aubergine', 'food', '茄子'],
  ['🍇', 'grapes', 'food', '葡萄'],
  ['🍈', 'melon', 'food', '哈密瓜,甜瓜'],
  ['🍉', 'watermelon', 'food', '西瓜'],
  ['🍊', 'tangerine', 'food', '橙子,橘子'],
  ['🍋', 'lemon', 'food', '柠檬'],
  ['🍌', 'banana', 'food', '香蕉'],
  ['🍍', 'pineapple', 'food', '菠萝'],
  ['🍎', 'red apple', 'food', '苹果'],
  ['🍏', 'green apple', 'food', ''],
  ['🍐', 'pear', 'food', '梨'],
  ['🍑', 'peach', 'food', '桃子,蜜桃'],
  ['🍒', 'cherries', 'food', '樱桃,车厘子'],
  ['🍓', 'strawberry', 'food', '草莓'],
  ['🍔', 'hamburger', 'food', '汉堡,汉堡包'],
  ['🍕', 'slice of pizza', 'food', '披萨,比萨'],
  ['🍖', 'meat on bone', 'food', '骨头,肉,排骨'],
  ['🍗', 'poultry leg', 'food', '鸡腿,炸鸡'],
  ['🍘', 'rice cracker', 'food', '米饼,仙贝'],
  ['🍙', 'rice ball', 'food', '饭团'],
  ['🍚', 'cooked rice', 'food', '米饭,饭'],
  ['🍛', 'curry and rice', 'food', '咖喱,咖喱饭'],
  ['🍜', 'steaming bowl', 'food', '面条,拉面,面'],
  ['🍝', 'spaghetti', 'food', '意大利面,意面'],
  ['🍞', 'bread', 'food', '面包'],
  ['🍟', 'french fries', 'food', '薯条,炸薯条'],
  ['🍠', 'roasted sweet potato', 'food', '红薯,地瓜'],
  ['🍡', 'dango', 'food', '团子,丸子'],
  ['🍢', 'oden', 'food', '关东煮,串'],
  ['🍣', 'sushi', 'food', '寿司,三文鱼'],
  ['🍤', 'fried shrimp', 'food', '炸虾,天妇罗'],
  ['🍥', 'fish cake with swirl design', 'food', '鱼板,鸣门卷'],
  ['🍦', 'soft ice cream', 'food', '冰淇淋,甜筒'],
  ['🍧', 'shaved ice', 'food', '刨冰,冰沙'],
  ['🍨', 'ice cream', 'food', '冰淇淋,圣代'],
  ['🍩', 'doughnut', 'food', ''],
  ['🍪', 'cookie', 'food', ''],
  ['🍫', 'chocolate bar', 'food', '巧克力'],
  ['🍬', 'candy', 'food', '糖果,糖'],
  ['🍭', 'lollipop', 'food', '棒棒糖'],
  ['🍮', 'custard', 'food', '布丁,焦糖'],
  ['🍯', 'honey pot', 'food', '蜂蜜,蜜'],
  ['🍰', 'shortcake', 'food', '蛋糕,奶油蛋糕'],
  ['🍱', 'bento box', 'food', '便当,盒饭'],
  ['🍲', 'pot of food', 'food', '火锅,汤锅,炖菜'],
  ['🍳', 'cooking', 'food', '煎蛋,鸡蛋'],
  ['🍴', 'fork and knife', 'food', '刀叉,餐具'],
  ['🍵', 'teacup without handle', 'food', '绿茶,茶,抹茶'],
  ['🍶', 'sake bottle and cup', 'food', '清酒,日本酒'],
  ['🍷', 'wine glass', 'food', '红酒,葡萄酒,酒'],
  ['🍸', 'cocktail glass', 'food', '鸡尾酒,马提尼'],
  ['🍹', 'tropical drink', 'food', '果汁,鸡尾酒'],
  ['🍺', 'beer mug', 'food', '啤酒,啤酒杯'],
  ['🍻', 'clinking beer mugs', 'food', '干杯,碰杯,啤酒'],
  ['🍼', 'baby bottle', 'food', '奶瓶,婴儿,奶粉'],
  ['🍽', 'fork and knife with plate', 'food', ''],
  ['🍾', 'bottle with popping cork', 'food', '香槟,起泡酒,庆祝'],
  ['🍿', 'popcorn', 'food', ''],
  ['🎀', 'ribbon', 'activity', '蝴蝶结,礼物,装饰'],
  ['🎁', 'wrapped present', 'activity', '礼物,礼盒,生日'],
  ['🎂', 'birthday cake', 'activity', '生日蛋糕,生日,蛋糕'],
  ['🎃', 'jack-o-lantern', 'activity', ''],
  ['🎄', 'christmas tree', 'activity', ''],
  ['🎅', 'father christmas', 'activity', '圣诞老人,圣诞,圣诞节'],
  ['🎆', 'fireworks', 'activity', ''],
  ['🎇', 'firework sparkler', 'activity', ''],
  ['🎈', 'balloon', 'activity', '气球,庆祝,派对'],
  ['🎉', 'party popper', 'activity', '彩带,庆祝,派对,欢呼'],
  ['🎊', 'confetti ball', 'activity', '庆祝'],
  ['🎋', 'tanabata tree', 'activity', ''],
  ['🎌', 'crossed flags', 'flags', '旗,日本,交叉旗'],
  ['🎍', 'pine decoration', 'activity', ''],
  ['🎎', 'japanese dolls', 'activity', '人偶,日本人偶'],
  ['🎏', 'carp streamer', 'activity', '鲤鱼旗,日本,端午节'],
  ['🎐', 'wind chime', 'activity', '风铃,夏天'],
  ['🎑', 'moon viewing ceremony', 'activity', ''],
  ['🎒', 'school satchel', 'activity', '书包,背包'],
  ['🎓', 'graduation cap', 'activity', '学士帽,毕业,学位'],
  ['🎖', 'military medal', 'activity', ''],
  ['🎗', 'reminder ribbon', 'activity', ''],
  ['🎙', 'studio microphone', 'activity', ''],
  ['🎚', 'level slider', 'activity', ''],
  ['🎛', 'control knobs', 'activity', ''],
  ['🎞', 'film frames', 'activity', ''],
  ['🎟', 'admission tickets', 'activity', ''],
  ['🎠', 'carousel horse', 'activity', '旋转木马,游乐园'],
  ['🎡', 'ferris wheel', 'activity', '摩天轮,游乐园'],
  ['🎢', 'roller coaster', 'activity', '过山车,游乐园'],
  ['🎣', 'fishing pole and fish', 'activity', '钓鱼'],
  ['🎤', 'microphone', 'activity', '麦克风,唱歌,K歌'],
  ['🎥', 'movie camera', 'activity', '摄影机,电影,拍摄'],
  ['🎦', 'cinema', 'activity', ''],
  ['🎧', 'headphone', 'activity', '耳机,听歌,音乐,戴'],
  ['🎨', 'artist palette', 'activity', '调色板,画画,美术,艺术'],
  ['🎩', 'top hat', 'activity', '礼帽,魔术帽,帽子'],
  ['🎪', 'circus tent', 'activity', '马戏团'],
  ['🎫', 'ticket', 'activity', '门票,票,入场券'],
  ['🎬', 'clapper board', 'activity', '场记板,电影,拍戏,导演'],
  ['🎭', 'performing arts', 'activity', '面具,戏剧,表演,舞台'],
  ['🎮', 'video game', 'activity', '游戏机,游戏,手柄,玩'],
  ['🎯', 'direct hit', 'activity', '目标'],
  ['🎰', 'slot machine', 'activity', ''],
  ['🎱', 'billiards', 'activity', '台球'],
  ['🎲', 'game die', 'activity', '骰子,赌博,游戏'],
  ['🎳', 'bowling', 'activity', '保龄球,球'],
  ['🎴', 'flower playing cards', 'activity', '花牌,卡牌,纸牌'],
  ['🎵', 'musical note', 'activity', '音符,音乐,歌'],
  ['🎶', 'multiple musical notes', 'activity', '音符,音乐,唱歌'],
  ['🎷', 'saxophone', 'activity', '萨克斯,爵士,乐器'],
  ['🎸', 'guitar', 'activity', '吉他,弹吉他,摇滚'],
  ['🎹', 'musical keyboard', 'activity', '钢琴,键盘,弹琴'],
  ['🎺', 'trumpet', 'activity', '小号,喇叭,乐器'],
  ['🎻', 'violin', 'activity', '小提琴,弦乐'],
  ['🎼', 'musical score', 'activity', '乐谱,音乐,谱'],
  ['🎽', 'running shirt with sash', 'activity', '背心'],
  ['🎾', 'tennis racquet and ball', 'activity', '网球,球'],
  ['🎿', 'ski and ski boot', 'activity', '滑雪'],
  ['🏀', 'basketball and hoop', 'activity', '篮球,球'],
  ['🏁', 'chequered flag', 'flags', '终点,旗帜,赛车,比赛'],
  ['🏂', 'snowboarder', 'activity', ''],
  ['🏃', 'runner', 'activity', '跑步,跑,奔跑'],
  ['🏄', 'surfer', 'activity', ''],
  ['🏅', 'sports medal', 'activity', '奖牌,奖章,荣誉'],
  ['🏆', 'trophy', 'activity', ''],
  ['🏇', 'horse racing', 'activity', ''],
  ['🏈', 'american football', 'activity', '橄榄球,美式足球'],
  ['🏉', 'rugby football', 'activity', '橄榄球,英式'],
  ['🏊', 'swimmer', 'activity', ''],
  ['🏋', 'weight lifter', 'activity', ''],
  ['🏌', 'golfer', 'activity', ''],
  ['🏍', 'racing motorcycle', 'activity', ''],
  ['🏎', 'racing car', 'activity', ''],
  ['🏏', 'cricket bat and ball', 'activity', ''],
  ['🏐', 'volleyball', 'activity', '排球,球'],
  ['🏑', 'field hockey stick and ball', 'activity', ''],
  ['🏒', 'ice hockey stick and puck', 'activity', ''],
  ['🏓', 'table tennis paddle and ball', 'activity', '乒乓球,乒乓,球'],
  ['🏔', 'snow capped mountain', 'activity', ''],
  ['🏕', 'camping', 'activity', ''],
  ['🏖', 'beach with umbrella', 'activity', ''],
  ['🏗', 'building construction', 'activity', ''],
  ['🏘', 'house buildings', 'activity', ''],
  ['🏙', 'cityscape', 'activity', ''],
  ['🏚', 'derelict house building', 'activity', ''],
  ['🏛', 'classical building', 'activity', ''],
  ['🏜', 'desert', 'activity', ''],
  ['🏝', 'desert island', 'activity', ''],
  ['🏞', 'national park', 'activity', ''],
  ['🏟', 'stadium', 'activity', ''],
  ['🏠', 'house building', 'travel', '房子,家,住宅'],
  ['🏡', 'house with garden', 'travel', '房子,家,花园'],
  ['🏢', 'office building', 'travel', '办公楼,大楼,写字楼'],
  ['🏣', 'japanese post office', 'travel', '邮局,邮政'],
  ['🏤', 'european post office', 'travel', '邮局'],
  ['🏥', 'hospital', 'travel', '医院,医疗'],
  ['🏦', 'bank', 'travel', '银行,金融'],
  ['🏧', 'automated teller machine', 'travel', ''],
  ['🏨', 'hotel', 'travel', '酒店,旅馆'],
  ['🏩', 'love hotel', 'travel', '爱情旅馆,酒店'],
  ['🏪', 'convenience store', 'travel', '便利店,商店'],
  ['🏫', 'school', 'travel', '学校,校园'],
  ['🏬', 'department store', 'travel', '商场,百货,购物'],
  ['🏭', 'factory', 'travel', '工厂,工业'],
  ['🏮', 'izakaya lantern', 'travel', ''],
  ['🏯', 'japanese castle', 'objects', '城堡,日本城堡'],
  ['🏰', 'european castle', 'travel', '城堡,童话'],
  ['🏳', 'waving white flag', 'flags', ''],
  ['🏴', 'waving black flag', 'flags', '黑旗'],
  ['🏵', 'rosette', 'objects', ''],
  ['🏷', 'label', 'objects', ''],
  ['🏸', 'badminton racquet and shuttlecock', 'activity', '羽毛球,球'],
  ['🏹', 'bow and arrow', 'activity', '射箭,弓箭,弓'],
  ['🏺', 'amphora', 'activity', '陶罐,花瓶,双耳瓶'],
  ['🏻', 'emoji modifier fitzpatrick type-1-2', 'symbols', ''],
  ['🏼', 'emoji modifier fitzpatrick type-3', 'symbols', ''],
  ['🏽', 'emoji modifier fitzpatrick type-4', 'symbols', ''],
  ['🏾', 'emoji modifier fitzpatrick type-5', 'symbols', ''],
  ['🏿', 'emoji modifier fitzpatrick type-6', 'symbols', ''],
  ['🐀', 'rat', 'animals', '老鼠,鼠'],
  ['🐁', 'mouse', 'animals', '老鼠,鼠'],
  ['🐂', 'ox', 'animals', '公牛,牛'],
  ['🐃', 'water buffalo', 'animals', '水牛,牛'],
  ['🐄', 'cow', 'animals', '奶牛,牛'],
  ['🐅', 'tiger', 'animals', ''],
  ['🐆', 'leopard', 'animals', ''],
  ['🐇', 'rabbit', 'animals', '兔子,兔'],
  ['🐈', 'cat', 'animals', '猫,猫咪'],
  ['🐉', 'dragon', 'animals', '龙,中国龙'],
  ['🐊', 'crocodile', 'animals', '鳄鱼,短吻鳄'],
  ['🐋', 'whale', 'animals', '鲸鱼'],
  ['🐌', 'snail', 'animals', ''],
  ['🐍', 'snake', 'animals', '蛇,爬行动物'],
  ['🐎', 'horse', 'animals', ''],
  ['🐏', 'ram', 'animals', '羊,公羊'],
  ['🐐', 'goat', 'animals', '山羊,羊'],
  ['🐑', 'sheep', 'animals', '羊,绵羊'],
  ['🐒', 'monkey', 'animals', ''],
  ['🐓', 'rooster', 'animals', '公鸡,鸡'],
  ['🐔', 'chicken', 'animals', '鸡,母鸡'],
  ['🐕', 'dog', 'animals', '狗,小狗'],
  ['🐖', 'pig', 'animals', '猪'],
  ['🐗', 'boar', 'animals', '野猪,猪'],
  ['🐘', 'elephant', 'animals', '大象'],
  ['🐙', 'octopus', 'animals', '章鱼,八爪鱼'],
  ['🐚', 'spiral shell', 'animals', ''],
  ['🐛', 'bug', 'animals', ''],
  ['🐜', 'ant', 'animals', ''],
  ['🐝', 'honeybee', 'animals', ''],
  ['🐞', 'lady beetle', 'animals', ''],
  ['🐟', 'fish', 'animals', '鱼,鱼'],
  ['🐠', 'tropical fish', 'animals', '热带鱼,鱼'],
  ['🐡', 'blowfish', 'animals', '河豚,鱼'],
  ['🐢', 'turtle', 'animals', '乌龟,慢'],
  ['🐣', 'hatching chick', 'animals', '小鸡,破壳,孵化'],
  ['🐤', 'baby chick', 'animals', '小鸡,黄,可爱'],
  ['🐥', 'front-facing baby chick', 'animals', '小鸡,正面'],
  ['🐦', 'bird', 'animals', '鸟'],
  ['🐧', 'penguin', 'animals', '企鹅,南极'],
  ['🐨', 'koala', 'animals', '考拉,无尾熊'],
  ['🐩', 'poodle', 'animals', '贵宾犬,狗'],
  ['🐪', 'dromedary camel', 'animals', '骆驼'],
  ['🐫', 'bactrian camel', 'animals', '骆驼,双峰'],
  ['🐬', 'dolphin', 'animals', '海豚,海洋'],
  ['🐭', 'mouse face', 'animals', '老鼠,鼠'],
  ['🐮', 'cow face', 'animals', '牛,奶牛'],
  ['🐯', 'tiger face', 'animals', ''],
  ['🐰', 'rabbit face', 'animals', '兔子,兔,可爱'],
  ['🐱', 'cat face', 'animals', ''],
  ['🐲', 'dragon face', 'animals', '龙,龙头'],
  ['🐳', 'spouting whale', 'animals', '鲸鱼,喷水'],
  ['🐴', 'horse face', 'animals', '马'],
  ['🐵', 'monkey face', 'animals', ''],
  ['🐶', 'dog face', 'animals', ''],
  ['🐷', 'pig face', 'animals', '猪,猪头'],
  ['🐸', 'frog face', 'animals', '青蛙,蛙'],
  ['🐹', 'hamster face', 'animals', '仓鼠'],
  ['🐺', 'wolf face', 'animals', ''],
  ['🐻', 'bear face', 'animals', '熊,泰迪熊'],
  ['🐼', 'panda face', 'animals', ''],
  ['🐽', 'pig nose', 'animals', '猪鼻子,猪'],
  ['🐾', 'paw prints', 'animals', '爪印,脚印'],
  ['🐿', 'chipmunk', 'animals', ''],
  ['👀', 'eyes', 'people', ''],
  ['👁', 'eye', 'people', ''],
  ['👂', 'ear', 'people', '耳朵,听'],
  ['👃', 'nose', 'people', '鼻子,闻'],
  ['👄', 'mouth', 'people', '嘴巴,嘴唇,吻'],
  ['👅', 'tongue', 'people', '舌头,舔'],
  ['👆', 'white up pointing backhand index', 'people', '指,上面,向上'],
  ['👇', 'white down pointing backhand index', 'people', '指,下面,向下'],
  ['👈', 'white left pointing backhand index', 'people', '指,左边,指向'],
  ['👉', 'white right pointing backhand index', 'people', '指,右边,指向'],
  ['👊', 'fisted hand sign', 'people', '拳头,打,战斗'],
  ['👋', 'waving hand sign', 'people', '挥手,再见,你好'],
  ['👌', 'ok hand sign', 'people', 'OK,好,可以'],
  ['👍', 'thumbs up sign', 'people', '点赞,好,赞,棒'],
  ['👎', 'thumbs down sign', 'people', '差评,不好,踩'],
  ['👏', 'clapping hands sign', 'people', '鼓掌,拍手,掌声'],
  ['👐', 'open hands sign', 'people', '张开,手,开放'],
  ['👑', 'crown', 'people', '皇冠,王冠,国王,女王'],
  ['👒', 'womans hat', 'people', '帽子,草帽,遮阳帽'],
  ['👓', 'eyeglasses', 'people', '眼镜'],
  ['👔', 'necktie', 'people', '领带,西装,工作'],
  ['👕', 't-shirt', 'people', '衣服,T恤'],
  ['👖', 'jeans', 'people', '裤子,牛仔裤'],
  ['👗', 'dress', 'people', '裙子,连衣裙'],
  ['👘', 'kimono', 'people', '和服'],
  ['👙', 'bikini', 'people', '比基尼,泳装'],
  ['👚', 'womans clothes', 'people', '女装,衣服'],
  ['👛', 'purse', 'people', '钱包,小包'],
  ['👜', 'handbag', 'people', '手提包,包包'],
  ['👝', 'pouch', 'people', '手拿包,包包'],
  ['👞', 'mans shoe', 'people', '皮鞋,鞋'],
  ['👟', 'athletic shoe', 'people', '运动鞋,跑鞋'],
  ['👠', 'high-heeled shoe', 'people', '高跟鞋,鞋'],
  ['👡', 'womans sandal', 'people', '凉鞋,鞋'],
  ['👢', 'womans boots', 'people', '靴子,长靴'],
  ['👣', 'footprints', 'people', '脚印,脚步,足迹'],
  ['👤', 'bust in silhouette', 'people', '人,剪影,用户'],
  ['👥', 'busts in silhouette', 'people', '人群,人,多个人'],
  ['👦', 'boy', 'people', '男孩,小男孩'],
  ['👧', 'girl', 'people', '女孩,小女孩'],
  ['👨', 'man', 'people', '男人,男士'],
  ['👩', 'woman', 'people', '女人,女士'],
  ['👪', 'family', 'people', '家庭'],
  ['👫', 'woman and man holding hands', 'people', ''],
  ['👬', 'men holding hands', 'people', ''],
  ['👭', 'women holding hands', 'people', ''],
  ['👮', 'police officer', 'people', '警察,警官'],
  ['👯', 'woman with bunny ears', 'people', '兔子舞,蹦迪,派对'],
  ['👰', 'bride with veil', 'people', '新娘,婚纱,结婚'],
  ['👱', 'person with blond hair', 'people', ''],
  ['👲', 'man with gua pi mao', 'people', '中国人'],
  ['👳', 'man with turban', 'people', '包头巾,印度,阿拉伯'],
  ['👴', 'older man', 'people', '老人,老爷爷'],
  ['👵', 'older woman', 'people', '老人,老奶奶'],
  ['👶', 'baby', 'people', '婴儿,宝宝,小孩'],
  ['👷', 'construction worker', 'people', '工人'],
  ['👸', 'princess', 'people', '公主,女王'],
  ['👹', 'japanese ogre', 'people', '妖怪,鬼,怪物'],
  ['👺', 'japanese goblin', 'people', '天狗,怪物,鬼'],
  ['👻', 'ghost', 'people', '幽灵,鬼,万圣节'],
  ['👼', 'baby angel', 'people', '天使,婴儿,可爱'],
  ['👽', 'extraterrestrial alien', 'people', '外星人,ET,飞碟'],
  ['👾', 'alien monster', 'people', '外星人,怪兽,游戏'],
  ['👿', 'imp', 'people', '恶魔,愤怒'],
  ['💀', 'skull', 'people', '骷髅,死亡,骨头'],
  ['💁', 'information desk person', 'people', ''],
  ['💂', 'guardsman', 'people', '卫兵,士兵'],
  ['💃', 'dancer', 'people', '跳舞,舞女,跳舞'],
  ['💄', 'lipstick', 'people', '口红,化妆'],
  ['💅', 'nail polish', 'people', '美甲,指甲,涂'],
  ['💆', 'face massage', 'people', '按摩,放松,头部'],
  ['💇', 'haircut', 'people', '理发,剪发,发型'],
  ['💈', 'barber pole', 'people', '理发店,理发'],
  ['💉', 'syringe', 'people', '注射器,针,疫苗'],
  ['💊', 'pill', 'people', '药丸,药,胶囊'],
  ['💋', 'kiss mark', 'people', '吻,口红印,亲亲'],
  ['💌', 'love letter', 'people', '情书,信,爱情'],
  ['💍', 'ring', 'people', '戒指,钻戒,结婚'],
  ['💎', 'gem stone', 'people', '钻石,宝石,珠宝'],
  ['💏', 'kiss', 'people', ''],
  ['💐', 'bouquet', 'smileys', '花束,花,礼物'],
  ['💑', 'couple with heart', 'smileys', ''],
  ['💒', 'wedding', 'smileys', '教堂,婚礼,教堂婚礼'],
  ['💓', 'beating heart', 'smileys', '爱心,跳动,心跳'],
  ['💔', 'broken heart', 'smileys', '心碎,伤心,破碎'],
  ['💕', 'two hearts', 'smileys', '爱心,两个,喜欢'],
  ['💖', 'sparkling heart', 'smileys', '爱心,闪光,喜欢'],
  ['💗', 'growing heart', 'smileys', '爱心,跳动,喜欢'],
  ['💘', 'heart with arrow', 'smileys', '爱心,箭,丘比特'],
  ['💙', 'blue heart', 'smileys', ''],
  ['💚', 'green heart', 'smileys', ''],
  ['💛', 'yellow heart', 'smileys', ''],
  ['💜', 'purple heart', 'smileys', ''],
  ['💝', 'heart with ribbon', 'smileys', '爱心,礼物,蝴蝶结'],
  ['💞', 'revolving hearts', 'smileys', '爱心,旋转,轮回'],
  ['💟', 'heart decoration', 'smileys', '爱心,符号'],
  ['💠', 'diamond shape with a dot inside', 'objects', ''],
  ['💡', 'electric light bulb', 'objects', ''],
  ['💢', 'anger symbol', 'objects', '生气,怒气'],
  ['💣', 'bomb', 'objects', '炸弹,爆炸'],
  ['💤', 'sleeping symbol', 'objects', '睡觉,打呼,困'],
  ['💥', 'collision symbol', 'objects', ''],
  ['💦', 'splashing sweat symbol', 'objects', '汗,水,泪'],
  ['💧', 'droplet', 'objects', '水滴,水,眼泪'],
  ['💨', 'dash symbol', 'objects', '风,跑,快,烟雾'],
  ['💩', 'pile of poo', 'objects', '大便,屎,狗屎'],
  ['💪', 'flexed biceps', 'people', '肌肉,力量,加油,强壮'],
  ['💫', 'dizzy symbol', 'objects', '星星,旋转'],
  ['💬', 'speech balloon', 'objects', '对话,聊天'],
  ['💭', 'thought balloon', 'objects', '想法,思考,气泡'],
  ['💮', 'white flower', 'objects', ''],
  ['💯', 'hundred points symbol', 'objects', ''],
  ['💰', 'money bag', 'objects', '钱袋,钱,金钱'],
  ['💱', 'currency exchange', 'objects', ''],
  ['💲', 'heavy dollar sign', 'objects', ''],
  ['💳', 'credit card', 'objects', '信用卡,银行卡,支付'],
  ['💴', 'banknote with yen sign', 'objects', '日元,日圆,钱'],
  ['💵', 'banknote with dollar sign', 'objects', '美元,美金,钱'],
  ['💶', 'banknote with euro sign', 'objects', '欧元,钱'],
  ['💷', 'banknote with pound sign', 'objects', '英镑,钱'],
  ['💸', 'money with wings', 'objects', '钱,飞钱,花钱'],
  ['💹', 'chart with upwards trend and yen sign', 'objects', '股票,上涨,图表,增长'],
  ['💺', 'seat', 'objects', '座位,椅子,飞机座位'],
  ['💻', 'personal computer', 'objects', '电脑,笔记本,笔记本电脑'],
  ['💼', 'briefcase', 'objects', '公文包,工作,商务'],
  ['💽', 'minidisc', 'objects', '光盘,磁盘'],
  ['💾', 'floppy disk', 'objects', '软盘,保存'],
  ['💿', 'optical disc', 'objects', '光盘,CD'],
  ['📀', 'dvd', 'objects', '光盘,DVD'],
  ['📁', 'file folder', 'objects', '文件夹'],
  ['📂', 'open file folder', 'objects', '文件夹,打开'],
  ['📃', 'page with curl', 'objects', '文件,文档'],
  ['📄', 'page facing up', 'objects', '文件,文档,纸'],
  ['📅', 'calendar', 'objects', '日历'],
  ['📆', 'tear-off calendar', 'objects', '日历,日历页'],
  ['📇', 'card index', 'objects', '名片,索引卡'],
  ['📈', 'chart with upwards trend', 'objects', ''],
  ['📉', 'chart with downwards trend', 'objects', ''],
  ['📊', 'bar chart', 'objects', ''],
  ['📋', 'clipboard', 'objects', '剪贴板,清单,列表'],
  ['📌', 'pushpin', 'objects', ''],
  ['📍', 'round pushpin', 'objects', ''],
  ['📎', 'paperclip', 'objects', ''],
  ['📏', 'straight ruler', 'objects', ''],
  ['📐', 'triangular ruler', 'objects', ''],
  ['📑', 'bookmark tabs', 'objects', '书签,标签,文件'],
  ['📒', 'ledger', 'objects', ''],
  ['📓', 'notebook', 'objects', ''],
  ['📔', 'notebook with decorative cover', 'objects', ''],
  ['📕', 'closed book', 'objects', ''],
  ['📖', 'open book', 'objects', ''],
  ['📗', 'green book', 'objects', ''],
  ['📘', 'blue book', 'objects', ''],
  ['📙', 'orange book', 'objects', ''],
  ['📚', 'books', 'objects', ''],
  ['📛', 'name badge', 'objects', ''],
  ['📜', 'scroll', 'objects', ''],
  ['📝', 'memo', 'objects', '笔记,备忘录,写作,文档'],
  ['📞', 'telephone receiver', 'objects', '电话'],
  ['📟', 'pager', 'objects', '寻呼机,传呼机'],
  ['📠', 'fax machine', 'objects', '传真机,传真'],
  ['📡', 'satellite antenna', 'objects', '天线,卫星,信号'],
  ['📢', 'public address loudspeaker', 'objects', ''],
  ['📣', 'cheering megaphone', 'objects', ''],
  ['📤', 'outbox tray', 'objects', '发送,输出,上传'],
  ['📥', 'inbox tray', 'objects', '接收,下载,收件箱'],
  ['📦', 'package', 'objects', '包裹,快递,箱子'],
  ['📧', 'e-mail symbol', 'objects', '邮件,电子邮件'],
  ['📨', 'incoming envelope', 'objects', '邮件,收到'],
  ['📩', 'envelope with downwards arrow above', 'objects', '邮件,发送'],
  ['📪', 'closed mailbox with lowered flag', 'objects', '邮箱,关闭'],
  ['📫', 'closed mailbox with raised flag', 'objects', '邮箱,信箱,邮件'],
  ['📬', 'open mailbox with raised flag', 'objects', '邮箱,有信'],
  ['📭', 'open mailbox with lowered flag', 'objects', '邮箱,无信'],
  ['📮', 'postbox', 'objects', '邮筒,邮政'],
  ['📯', 'postal horn', 'objects', ''],
  ['📰', 'newspaper', 'objects', '报纸,新闻,报'],
  ['📱', 'mobile phone', 'objects', '手机,智能手机,电话'],
  ['📲', 'mobile phone with rightwards arrow at left', 'objects', '手机,接收,信号'],
  ['📳', 'vibration mode', 'objects', ''],
  ['📴', 'mobile phone off', 'objects', ''],
  ['📵', 'no mobile phones', 'objects', ''],
  ['📶', 'antenna with bars', 'objects', ''],
  ['📷', 'camera', 'objects', '相机,拍照,照片'],
  ['📸', 'camera with flash', 'objects', '相机,闪光灯,拍照'],
  ['📹', 'video camera', 'objects', '摄像机,录像'],
  ['📺', 'television', 'objects', ''],
  ['📻', 'radio', 'objects', '收音机,广播'],
  ['📼', 'videocassette', 'objects', '录像带,磁带'],
  ['📽', 'film projector', 'objects', ''],
  ['📿', 'prayer beads', 'objects', '念珠,佛珠,项链'],
  ['🔀', 'twisted rightwards arrows', 'objects', ''],
  ['🔁', 'clockwise rightwards and leftwards open circle arrows', 'objects', ''],
  ['🔂', 'clockwise rightwards and leftwards open circle arrows with circled one overlay', 'objects', ''],
  ['🔃', 'clockwise downwards and upwards open circle arrows', 'objects', ''],
  ['🔄', 'anticlockwise downwards and upwards open circle arrows', 'objects', ''],
  ['🔅', 'low brightness symbol', 'objects', ''],
  ['🔆', 'high brightness symbol', 'objects', ''],
  ['🔇', 'speaker with cancellation stroke', 'objects', ''],
  ['🔈', 'speaker', 'objects', ''],
  ['🔉', 'speaker with one sound wave', 'objects', ''],
  ['🔊', 'speaker with three sound waves', 'objects', ''],
  ['🔋', 'battery', 'objects', ''],
  ['🔌', 'electric plug', 'objects', ''],
  ['🔍', 'left-pointing magnifying glass', 'objects', '搜索,放大镜,查找,查询'],
  ['🔎', 'right-pointing magnifying glass', 'objects', '搜索,放大镜,查找'],
  ['🔏', 'lock with ink pen', 'objects', '锁,保密,笔'],
  ['🔐', 'closed lock with key', 'objects', '锁,安全,钥匙'],
  ['🔑', 'key', 'objects', '钥匙,解锁'],
  ['🔒', 'lock', 'objects', '锁,锁定,安全'],
  ['🔓', 'open lock', 'objects', '解锁,打开'],
  ['🔔', 'bell', 'objects', ''],
  ['🔕', 'bell with cancellation stroke', 'objects', ''],
  ['🔖', 'bookmark', 'objects', '书签,标记'],
  ['🔗', 'link symbol', 'objects', ''],
  ['🔘', 'radio button', 'objects', ''],
  ['🔙', 'back with leftwards arrow above', 'objects', ''],
  ['🔚', 'end with leftwards arrow above', 'objects', ''],
  ['🔛', 'on with exclamation mark with left right arrow above', 'objects', ''],
  ['🔜', 'soon with rightwards arrow above', 'objects', ''],
  ['🔝', 'top with upwards arrow above', 'objects', ''],
  ['🔞', 'no one under eighteen symbol', 'objects', ''],
  ['🔟', 'keycap 10', 'objects', ''],
  ['🔠', 'input symbol for latin capital letters', 'objects', ''],
  ['🔡', 'input symbol for latin small letters', 'objects', ''],
  ['🔢', 'input symbol for numbers', 'objects', ''],
  ['🔣', 'input symbol for symbols', 'objects', ''],
  ['🔤', 'input symbol for latin letters', 'objects', ''],
  ['🔥', 'fire', 'objects', ''],
  ['🔦', 'electric torch', 'objects', ''],
  ['🔧', 'wrench', 'objects', '扳手,工具,维修'],
  ['🔨', 'hammer', 'objects', '锤子,工具'],
  ['🔩', 'nut and bolt', 'objects', '螺丝,螺母'],
  ['🔪', 'hocho', 'objects', ''],
  ['🔫', 'pistol', 'objects', '枪'],
  ['🔬', 'microscope', 'objects', '显微镜,科学,研究'],
  ['🔭', 'telescope', 'objects', '望远镜,天文,观察'],
  ['🔮', 'crystal ball', 'objects', ''],
  ['🔯', 'six pointed star with middle dot', 'objects', ''],
  ['🔰', 'japanese symbol for beginner', 'objects', ''],
  ['🔱', 'trident emblem', 'objects', ''],
  ['🔲', 'black square button', 'objects', ''],
  ['🔳', 'white square button', 'objects', ''],
  ['🔴', 'large red circle', 'objects', ''],
  ['🔵', 'large blue circle', 'objects', ''],
  ['🔶', 'large orange diamond', 'objects', ''],
  ['🔷', 'large blue diamond', 'objects', ''],
  ['🔸', 'small orange diamond', 'objects', ''],
  ['🔹', 'small blue diamond', 'objects', ''],
  ['🔺', 'up-pointing red triangle', 'objects', ''],
  ['🔻', 'down-pointing red triangle', 'objects', ''],
  ['🔼', 'up-pointing small red triangle', 'objects', ''],
  ['🔽', 'down-pointing small red triangle', 'objects', ''],
  ['🕉', 'om symbol', 'objects', ''],
  ['🕊', 'dove of peace', 'objects', ''],
  ['🕋', 'kaaba', 'objects', '天房,麦加,伊斯兰'],
  ['🕌', 'mosque', 'objects', '清真寺,伊斯兰'],
  ['🕍', 'synagogue', 'objects', '犹太教堂,犹太'],
  ['🕎', 'menorah with nine branches', 'objects', ''],
  ['🕐', 'clock face one oclock', 'objects', '一点,时钟'],
  ['🕑', 'clock face two oclock', 'objects', '两点,时钟'],
  ['🕒', 'clock face three oclock', 'objects', '三点,时钟'],
  ['🕓', 'clock face four oclock', 'objects', '四点,时钟'],
  ['🕔', 'clock face five oclock', 'objects', '五点,时钟'],
  ['🕕', 'clock face six oclock', 'objects', '六点,时钟'],
  ['🕖', 'clock face seven oclock', 'objects', '七点,时钟'],
  ['🕗', 'clock face eight oclock', 'objects', '八点,时钟'],
  ['🕘', 'clock face nine oclock', 'objects', '九点,时钟'],
  ['🕙', 'clock face ten oclock', 'objects', '十点,时钟'],
  ['🕚', 'clock face eleven oclock', 'objects', '十一点,时钟'],
  ['🕛', 'clock face twelve oclock', 'objects', '十二点,时钟,时间'],
  ['🕜', 'clock face one-thirty', 'objects', ''],
  ['🕝', 'clock face two-thirty', 'objects', ''],
  ['🕞', 'clock face three-thirty', 'objects', ''],
  ['🕟', 'clock face four-thirty', 'objects', ''],
  ['🕠', 'clock face five-thirty', 'objects', ''],
  ['🕡', 'clock face six-thirty', 'objects', ''],
  ['🕢', 'clock face seven-thirty', 'objects', ''],
  ['🕣', 'clock face eight-thirty', 'objects', ''],
  ['🕤', 'clock face nine-thirty', 'objects', ''],
  ['🕥', 'clock face ten-thirty', 'objects', ''],
  ['🕦', 'clock face eleven-thirty', 'objects', ''],
  ['🕧', 'clock face twelve-thirty', 'objects', ''],
  ['🕯', 'candle', 'objects', ''],
  ['🕰', 'mantelpiece clock', 'objects', ''],
  ['🕳', 'hole', 'objects', ''],
  ['🕴', 'man in business suit levitating', 'objects', ''],
  ['🕵', 'sleuth or spy', 'objects', ''],
  ['🕶', 'dark sunglasses', 'objects', ''],
  ['🕷', 'spider', 'objects', ''],
  ['🕸', 'spider web', 'objects', ''],
  ['🕹', 'joystick', 'objects', ''],
  ['🕺', 'man dancing', 'objects', '跳舞,舞男'],
  ['🖇', 'linked paperclips', 'objects', ''],
  ['🖊', 'lower left ballpoint pen', 'objects', ''],
  ['🖋', 'lower left fountain pen', 'objects', ''],
  ['🖌', 'lower left paintbrush', 'objects', ''],
  ['🖍', 'lower left crayon', 'objects', ''],
  ['🖐', 'raised hand with fingers splayed', 'objects', ''],
  ['🖕', 'reversed hand with middle finger extended', 'objects', '中指,骂人'],
  ['🖖', 'raised hand with part between middle and ring fingers', 'objects', '瓦肯,举手,胜利'],
  ['🖤', 'black heart', 'objects', ''],
  ['🖥', 'desktop computer', 'objects', ''],
  ['🖨', 'printer', 'objects', ''],
  ['🖱', 'three button mouse', 'objects', ''],
  ['🖲', 'trackball', 'objects', ''],
  ['🖼', 'frame with picture', 'objects', ''],
  ['🗂', 'card index dividers', 'objects', ''],
  ['🗃', 'card file box', 'objects', ''],
  ['🗄', 'file cabinet', 'objects', ''],
  ['🗑', 'wastebasket', 'objects', ''],
  ['🗒', 'spiral note pad', 'objects', ''],
  ['🗓', 'spiral calendar pad', 'objects', ''],
  ['🗜', 'compression', 'objects', ''],
  ['🗝', 'old key', 'objects', ''],
  ['🗞', 'rolled-up newspaper', 'objects', ''],
  ['🗡', 'dagger knife', 'objects', ''],
  ['🗣', 'speaking head in silhouette', 'objects', ''],
  ['🗨', 'left speech bubble', 'objects', ''],
  ['🗯', 'right anger bubble', 'objects', ''],
  ['🗳', 'ballot box with ballot', 'objects', ''],
  ['🗺', 'world map', 'objects', ''],
  ['🗻', 'mount fuji', 'objects', '富士山,山'],
  ['🗼', 'tokyo tower', 'objects', '塔,东京塔'],
  ['🗽', 'statue of liberty', 'objects', '自由女神像,纽约'],
  ['🗾', 'silhouette of japan', 'objects', ''],
  ['🗿', 'moyai', 'objects', '雕像'],
  ['😀', 'grinning face', 'smileys', '笑脸,开心,高兴'],
  ['😁', 'grinning face with smiling eyes', 'smileys', '笑脸,开心'],
  ['😂', 'face with tears of joy', 'smileys', '笑哭,大笑,笑'],
  ['😃', 'smiling face with open mouth', 'smileys', '笑脸,开心'],
  ['😄', 'smiling face with open mouth and smiling eyes', 'smileys', '笑脸,开心'],
  ['😅', 'smiling face with open mouth and cold sweat', 'smileys', '笑脸,汗,尴尬'],
  ['😆', 'smiling face with open mouth and tightly-closed eyes', 'smileys', '笑脸,大笑'],
  ['😇', 'smiling face with halo', 'smileys', '天使,微笑,善良'],
  ['😈', 'smiling face with horns', 'smileys', '恶魔,坏笑,邪恶'],
  ['😉', 'winking face', 'smileys', '眨眼,调皮'],
  ['😊', 'smiling face with smiling eyes', 'smileys', '微笑,开心,脸红'],
  ['😋', 'face savouring delicious food', 'smileys', '好吃,美味,舔'],
  ['😌', 'relieved face', 'smileys', '放松,安心'],
  ['😍', 'smiling face with heart-shaped eyes', 'smileys', '爱,喜欢,花痴'],
  ['😎', 'smiling face with sunglasses', 'smileys', '酷,墨镜,帅气'],
  ['😏', 'smirking face', 'smileys', '得意,微笑,坏笑'],
  ['😐', 'neutral face', 'smileys', '无语,面无表情'],
  ['😑', 'expressionless face', 'smileys', '无语,面无表情'],
  ['😒', 'unamused face', 'smileys', '不满,无语,翻白眼'],
  ['😓', 'face with cold sweat', 'smileys', '冷汗,尴尬'],
  ['😔', 'pensive face', 'smileys', '难过,低落'],
  ['😕', 'confused face', 'smileys', '困惑,不解'],
  ['😖', 'confounded face', 'smileys', '纠结,痛苦'],
  ['😗', 'kissing face', 'smileys', '亲亲,吻'],
  ['😘', 'face throwing a kiss', 'smileys', '飞吻,亲亲,爱'],
  ['😙', 'kissing face with smiling eyes', 'smileys', ''],
  ['😚', 'kissing face with closed eyes', 'smileys', '亲亲,吻'],
  ['😛', 'face with stuck-out tongue', 'smileys', '吐舌头,调皮'],
  ['😜', 'face with stuck-out tongue and winking eye', 'smileys', '吐舌头,调皮,眨眼'],
  ['😝', 'face with stuck-out tongue and tightly-closed eyes', 'smileys', '吐舌头,调皮'],
  ['😞', 'disappointed face', 'smileys', '失望,难过'],
  ['😟', 'worried face', 'smileys', '担心,忧虑'],
  ['😠', 'angry face', 'smileys', '生气,愤怒'],
  ['😡', 'pouting face', 'smileys', '生气,愤怒,红脸'],
  ['😢', 'crying face', 'smileys', '哭,伤心,流泪'],
  ['😣', 'persevering face', 'smileys', '挣扎,痛苦'],
  ['😤', 'face with look of triumph', 'smileys', '生气,冒烟,气'],
  ['😥', 'disappointed but relieved face', 'smileys', '难过,失望,松气'],
  ['😦', 'frowning face with open mouth', 'smileys', '惊讶,张嘴'],
  ['😧', 'anguished face', 'smileys', '震惊,痛苦'],
  ['😨', 'fearful face', 'smileys', '害怕,恐惧'],
  ['😩', 'weary face', 'smileys', '累,疲惫,哭'],
  ['😪', 'sleepy face', 'smileys', '困,想睡'],
  ['😫', 'tired face', 'smileys', '累,疲惫'],
  ['😬', 'grimacing face', 'smileys', '尴尬,咧嘴'],
  ['😭', 'loudly crying face', 'smileys', '大哭,伤心,哭'],
  ['😮', 'face with open mouth', 'smileys', '惊讶,哇'],
  ['😯', 'hushed face', 'smileys', '惊讶,安静'],
  ['😰', 'face with open mouth and cold sweat', 'smileys', '担心,冷汗'],
  ['😱', 'face screaming in fear', 'smileys', '尖叫,害怕,恐怖'],
  ['😲', 'astonished face', 'smileys', '震惊,惊讶'],
  ['😳', 'flushed face', 'smileys', '脸红,害羞,震惊'],
  ['😴', 'sleeping face', 'smileys', '睡觉,睡觉'],
  ['😵', 'dizzy face', 'smileys', '晕,头晕,死'],
  ['😶', 'face without mouth', 'smileys', '沉默,无语'],
  ['😷', 'face with medical mask', 'smileys', '生病,口罩,感冒'],
  ['😸', 'grinning cat face with smiling eyes', 'smileys', '猫,笑脸'],
  ['😹', 'cat face with tears of joy', 'smileys', '猫,笑哭'],
  ['😺', 'smiling cat face with open mouth', 'smileys', '猫,笑脸,开心'],
  ['😻', 'smiling cat face with heart-shaped eyes', 'smileys', '猫,爱,喜欢'],
  ['😼', 'cat face with wry smile', 'smileys', '猫,坏笑'],
  ['😽', 'kissing cat face with closed eyes', 'smileys', '猫,亲亲'],
  ['😾', 'pouting cat face', 'smileys', '猫,生气'],
  ['😿', 'crying cat face', 'smileys', '猫,哭,伤心'],
  ['🙀', 'weary cat face', 'smileys', '猫,震惊,害怕'],
  ['🙁', 'slightly frowning face', 'smileys', '难过,失望'],
  ['🙂', 'slightly smiling face', 'smileys', '微笑,笑'],
  ['🙃', 'upside-down face', 'smileys', '微笑,倒'],
  ['🙄', 'face with rolling eyes', 'smileys', '翻白眼,无语'],
  ['🙅', 'face with no good gesture', 'smileys', ''],
  ['🙆', 'face with ok gesture', 'smileys', ''],
  ['🙇', 'person bowing deeply', 'smileys', ''],
  ['🙈', 'see-no-evil monkey', 'smileys', ''],
  ['🙉', 'hear-no-evil monkey', 'smileys', ''],
  ['🙊', 'speak-no-evil monkey', 'smileys', ''],
  ['🙋', 'happy person raising one hand', 'smileys', ''],
  ['🙌', 'person raising both hands in celebration', 'smileys', '欢呼,举起,庆祝'],
  ['🙍', 'person frowning', 'smileys', ''],
  ['🙎', 'person with pouting face', 'smileys', ''],
  ['🙏', 'person with folded hands', 'smileys', '祈祷,拜托,感谢,合十'],
  ['🚀', 'rocket', 'travel', '火箭,发射,太空'],
  ['🚁', 'helicopter', 'travel', '直升机'],
  ['🚂', 'steam locomotive', 'travel', '火车,蒸汽火车'],
  ['🚃', 'railway car', 'travel', '电车,火车'],
  ['🚄', 'high-speed train', 'travel', '高铁,动车,火车'],
  ['🚅', 'high-speed train with bullet nose', 'travel', ''],
  ['🚆', 'train', 'travel', '火车,铁路'],
  ['🚇', 'metro', 'travel', '地铁,地铁站'],
  ['🚈', 'light rail', 'travel', '轻轨,轨道交通'],
  ['🚉', 'station', 'travel', '火车站,车站'],
  ['🚊', 'tram', 'travel', '电车'],
  ['🚋', 'tram car', 'travel', '电车,有轨电车'],
  ['🚌', 'bus', 'travel', '公交车,巴士'],
  ['🚍', 'oncoming bus', 'travel', '公交车'],
  ['🚎', 'trolleybus', 'travel', '无轨电车,巴士'],
  ['🚏', 'bus stop', 'travel', '公交站,车站'],
  ['🚐', 'minibus', 'travel', '面包车,小巴'],
  ['🚑', 'ambulance', 'travel', '救护车,急救'],
  ['🚒', 'fire engine', 'travel', '消防车,救火'],
  ['🚓', 'police car', 'travel', '警车,警察'],
  ['🚔', 'oncoming police car', 'travel', '警车,巡逻'],
  ['🚕', 'taxi', 'travel', '出租车,的士'],
  ['🚖', 'oncoming taxi', 'travel', '出租车'],
  ['🚗', 'automobile', 'travel', '汽车,轿车,车'],
  ['🚘', 'oncoming automobile', 'travel', '汽车'],
  ['🚙', 'recreational vehicle', 'travel', 'SUV,越野车,汽车'],
  ['🚚', 'delivery truck', 'travel', '卡车,货车'],
  ['🚛', 'articulated lorry', 'travel', '卡车,货车'],
  ['🚜', 'tractor', 'travel', '拖拉机,农用'],
  ['🚝', 'monorail', 'travel', '单轨,单轨列车'],
  ['🚞', 'mountain railway', 'travel', '火车,山区铁路'],
  ['🚟', 'suspension railway', 'travel', '缆车,悬挂列车'],
  ['🚠', 'mountain cableway', 'travel', '缆车,高山'],
  ['🚡', 'aerial tramway', 'travel', '缆车,索道'],
  ['🚢', 'ship', 'travel', '轮船,船,大海'],
  ['🚣', 'rowboat', 'travel', ''],
  ['🚤', 'speedboat', 'travel', '快艇,汽艇'],
  ['🚥', 'horizontal traffic light', 'travel', '红绿灯,交通信号灯'],
  ['🚦', 'vertical traffic light', 'travel', '红绿灯,信号灯'],
  ['🚧', 'construction sign', 'travel', '施工,施工中,路障'],
  ['🚨', 'police cars revolving light', 'travel', '警车灯,警报,紧急'],
  ['🚩', 'triangular flag on post', 'travel', '红旗,旗帜,标志'],
  ['🚪', 'door', 'travel', '门,房门'],
  ['🚫', 'no entry sign', 'travel', ''],
  ['🚬', 'smoking symbol', 'travel', '香烟,烟,吸烟'],
  ['🚭', 'no smoking symbol', 'travel', ''],
  ['🚮', 'put litter in its place symbol', 'travel', '垃圾,清理'],
  ['🚯', 'do not litter symbol', 'travel', ''],
  ['🚰', 'potable water symbol', 'travel', ''],
  ['🚱', 'non-potable water symbol', 'travel', ''],
  ['🚲', 'bicycle', 'travel', '自行车,单车,骑行'],
  ['🚳', 'no bicycles', 'travel', ''],
  ['🚴', 'bicyclist', 'travel', ''],
  ['🚵', 'mountain bicyclist', 'travel', ''],
  ['🚶', 'pedestrian', 'travel', '走路,步行,散步'],
  ['🚷', 'no pedestrians', 'travel', ''],
  ['🚸', 'children crossing', 'travel', ''],
  ['🚹', 'mens symbol', 'travel', ''],
  ['🚺', 'womens symbol', 'travel', ''],
  ['🚻', 'restroom', 'travel', ''],
  ['🚼', 'baby symbol', 'travel', ''],
  ['🚽', 'toilet', 'travel', '马桶,厕所,卫生间'],
  ['🚾', 'water closet', 'travel', ''],
  ['🚿', 'shower', 'travel', '淋浴,洗澡'],
  ['🛀', 'bath', 'travel', '泡澡'],
  ['🛁', 'bathtub', 'travel', '浴缸,洗澡,泡澡'],
  ['🛂', 'passport control', 'travel', ''],
  ['🛃', 'customs', 'travel', ''],
  ['🛄', 'baggage claim', 'travel', ''],
  ['🛅', 'left luggage', 'travel', ''],
  ['🛋', 'couch and lamp', 'travel', ''],
  ['🛌', 'sleeping accommodation', 'travel', '睡觉'],
  ['🛍', 'shopping bags', 'travel', ''],
  ['🛎', 'bellhop bell', 'travel', ''],
  ['🛏', 'bed', 'travel', ''],
  ['🛐', 'place of worship', 'travel', ''],
  ['🛑', 'octagonal sign', 'travel', '停止,停车,红圈'],
  ['🛒', 'shopping trolley', 'travel', '购物车,购物'],
  ['🛕', 'hindu temple', 'travel', '印度教神庙'],
  ['🛖', 'hut', 'travel', '草屋,小屋'],
  ['🛗', 'elevator', 'travel', ''],
  ['🛜', 'wireless', 'travel', ''],
  ['🛝', 'playground slide', 'travel', ''],
  ['🛞', 'wheel', 'travel', '车轮,轮胎'],
  ['🛟', 'ring buoy', 'travel', '救生圈,救生'],
  ['🛠', 'hammer and wrench', 'travel', ''],
  ['🛡', 'shield', 'travel', ''],
  ['🛢', 'oil drum', 'travel', ''],
  ['🛣', 'motorway', 'travel', ''],
  ['🛤', 'railway track', 'travel', ''],
  ['🛥', 'motor boat', 'travel', ''],
  ['🛩', 'small airplane', 'travel', ''],
  ['🛫', 'airplane departure', 'travel', '起飞,飞机,出发'],
  ['🛬', 'airplane arriving', 'travel', '降落,飞机,到达'],
  ['🛰', 'satellite', 'travel', ''],
  ['🛳', 'passenger ship', 'travel', ''],
  ['🛴', 'scooter', 'travel', '滑板车,平衡车'],
  ['🛵', 'motor scooter', 'travel', '摩托车,电动车,踏板车'],
  ['🛶', 'canoe', 'travel', '独木舟,皮划艇'],
  ['🛷', 'sled', 'travel', '雪橇,雪车'],
  ['🛸', 'flying saucer', 'travel', '飞碟,UFO,外星人'],
  ['🛹', 'skateboard', 'travel', '滑板'],
  ['🛺', 'auto rickshaw', 'travel', '三轮车,突突车'],
  ['🛻', 'pickup truck', 'travel', '皮卡,卡车'],
  ['🛼', 'roller skate', 'travel', '轮滑'],
  ['🟠', 'large orange circle', 'symbols', ''],
  ['🟡', 'large yellow circle', 'symbols', ''],
  ['🟢', 'large green circle', 'symbols', ''],
  ['🟣', 'large purple circle', 'symbols', ''],
  ['🟤', 'large brown circle', 'symbols', ''],
  ['🟥', 'large red square', 'symbols', ''],
  ['🟦', 'large blue square', 'symbols', ''],
  ['🟧', 'large orange square', 'symbols', ''],
  ['🟨', 'large yellow square', 'symbols', ''],
  ['🟩', 'large green square', 'symbols', ''],
  ['🟪', 'large purple square', 'symbols', ''],
  ['🟫', 'large brown square', 'symbols', ''],
  ['🟰', 'heavy equals sign', 'symbols', ''],
  ['🤌', 'pinched fingers', 'symbols', '手指,捏,意大利'],
  ['🤍', 'white heart', 'symbols', '白心,白色,爱心'],
  ['🤎', 'brown heart', 'symbols', '棕心,棕色,爱心'],
  ['🤏', 'pinching hand', 'symbols', '捏,一点点,微小'],
  ['🤐', 'zipper-mouth face', 'smileys', '闭嘴,不说'],
  ['🤑', 'money-mouth face', 'smileys', '发财,金钱,贪婪'],
  ['🤒', 'face with thermometer', 'smileys', '发烧,生病,温度计'],
  ['🤓', 'nerd face', 'smileys', '书呆子,眼镜'],
  ['🤔', 'thinking face', 'smileys', '思考,疑问,想'],
  ['🤕', 'face with head-bandage', 'smileys', '受伤,包扎,头'],
  ['🤖', 'robot face', 'smileys', '机器人,AI,机械'],
  ['🤗', 'hugging face', 'smileys', '拥抱,欢迎'],
  ['🤘', 'sign of the horns', 'smileys', '摇滚,手势,牛'],
  ['🤙', 'call me hand', 'smileys', '打电话,挂,酷'],
  ['🤚', 'raised back of hand', 'smileys', '手,举手,停'],
  ['🤛', 'left-facing fist', 'smileys', '拳头,左边'],
  ['🤜', 'right-facing fist', 'smileys', '拳头,右边'],
  ['🤝', 'handshake', 'smileys', '握手,合作,协议'],
  ['🤞', 'hand with index and middle fingers crossed', 'smileys', '祈祷,好运,手指交叉'],
  ['🤟', 'i love you hand sign', 'smileys', '爱你,摇滚'],
  ['🤠', 'face with cowboy hat', 'smileys', '牛仔,帽子'],
  ['🤡', 'clown face', 'smileys', '小丑,马戏团'],
  ['🤢', 'nauseated face', 'smileys', '恶心,呕吐'],
  ['🤣', 'rolling on the floor laughing', 'smileys', '笑哭,大笑,笑'],
  ['🤤', 'drooling face', 'smileys', '流口水,馋'],
  ['🤥', 'lying face', 'smileys', '说谎,撒谎'],
  ['🤦', 'face palm', 'smileys', '捂脸,无奈,扶额'],
  ['🤧', 'sneezing face', 'smileys', '打喷嚏,感冒'],
  ['🤨', 'face with one eyebrow raised', 'symbols', '怀疑,挑眉'],
  ['🤩', 'grinning face with star eyes', 'symbols', '星星眼,兴奋,惊讶'],
  ['🤪', 'grinning face with one large and one small eye', 'symbols', '疯狂,搞怪'],
  ['🤫', 'face with finger covering closed lips', 'symbols', '嘘,安静'],
  ['🤬', 'serious face with symbols covering mouth', 'symbols', '骂人,脏话,生气'],
  ['🤭', 'smiling face with smiling eyes and hand covering mouth', 'symbols', '捂嘴,偷笑,惊讶'],
  ['🤮', 'face with open mouth vomiting', 'symbols', '呕吐,恶心'],
  ['🤯', 'shocked face with exploding head', 'smileys', '爆炸,震惊,头炸'],
  ['🤰', 'pregnant woman', 'people', '孕妇,怀孕'],
  ['🤱', 'breast-feeding', 'people', ''],
  ['🤲', 'palms up together', 'people', ''],
  ['🤳', 'selfie', 'people', '自拍,拍照'],
  ['🤴', 'prince', 'people', '王子,国王'],
  ['🤵', 'man in tuxedo', 'people', '新郎,西装,燕尾服'],
  ['🤶', 'mother christmas', 'people', '圣诞奶奶,圣诞老人'],
  ['🤷', 'shrug', 'people', '耸肩,无奈,不知道'],
  ['🤸', 'person doing cartwheel', 'people', '翻跟头,体操,空翻'],
  ['🤹', 'juggling', 'people', '杂耍'],
  ['🤺', 'fencer', 'people', '击剑,剑术'],
  ['🤼', 'wrestlers', 'activity', '摔跤,格斗'],
  ['🤽', 'water polo', 'activity', ''],
  ['🤾', 'handball', 'activity', ''],
  ['🤿', 'diving mask', 'activity', '潜水面罩,潜水'],
  ['🥀', 'wilted flower', 'symbols', ''],
  ['🥁', 'drum with drumsticks', 'symbols', '鼓,打鼓,乐器'],
  ['🥂', 'clinking glasses', 'symbols', '干杯,香槟杯'],
  ['🥃', 'tumbler glass', 'symbols', '威士忌,酒杯'],
  ['🥄', 'spoon', 'symbols', '勺子,汤匙'],
  ['🥅', 'goal net', 'symbols', '球门,网,进球'],
  ['🥇', 'first place medal', 'symbols', '金牌,冠军,第一名,奖牌'],
  ['🥈', 'second place medal', 'symbols', '银牌,第二名,奖牌'],
  ['🥉', 'third place medal', 'symbols', '铜牌,第三名,奖牌'],
  ['🥊', 'boxing glove', 'symbols', '拳击,拳击手套,打拳'],
  ['🥋', 'martial arts uniform', 'symbols', '道服,武术,空手道'],
  ['🥌', 'curling stone', 'symbols', '冰壶,冰壶'],
  ['🥍', 'lacrosse stick and ball', 'symbols', ''],
  ['🥎', 'softball', 'symbols', '垒球,球'],
  ['🥏', 'flying disc', 'symbols', '飞盘,飞碟'],
  ['🥐', 'croissant', 'food', '牛角包,可颂'],
  ['🥑', 'avocado', 'food', '牛油果,鳄梨'],
  ['🥒', 'cucumber', 'food', '黄瓜'],
  ['🥓', 'bacon', 'food', '培根,腊肉'],
  ['🥔', 'potato', 'food', '土豆,马铃薯'],
  ['🥕', 'carrot', 'food', '胡萝卜'],
  ['🥖', 'baguette bread', 'food', '法棍,面包'],
  ['🥗', 'green salad', 'food', '沙拉,蔬菜'],
  ['🥘', 'shallow pan of food', 'food', '炖锅,海鲜饭'],
  ['🥙', 'stuffed flatbread', 'food', '卷饼,肉夹馍'],
  ['🥚', 'egg', 'food', '鸡蛋,蛋'],
  ['🥛', 'glass of milk', 'food', '牛奶,奶'],
  ['🥜', 'peanuts', 'food', ''],
  ['🥝', 'kiwifruit', 'food', '猕猴桃,奇异果'],
  ['🥞', 'pancakes', 'food', '松饼,煎饼'],
  ['🥟', 'dumpling', 'food', '饺子,锅贴'],
  ['🥠', 'fortune cookie', 'food', '幸运饼干'],
  ['🥡', 'takeout box', 'food', ''],
  ['🥢', 'chopsticks', 'food', '筷子'],
  ['🥣', 'bowl with spoon', 'food', ''],
  ['🥤', 'cup with straw', 'food', '饮料,杯'],
  ['🥥', 'coconut', 'food', '椰子'],
  ['🥦', 'broccoli', 'food', '西兰花'],
  ['🥧', 'pie', 'food', '派,馅饼'],
  ['🥨', 'pretzel', 'food', '椒盐卷饼'],
  ['🥩', 'cut of meat', 'food', '牛排,肉'],
  ['🥪', 'sandwich', 'food', '三明治'],
  ['🥫', 'canned food', 'food', '罐头,罐装'],
  ['🥬', 'leafy green', 'symbols', '青菜,白菜,生菜'],
  ['🥭', 'mango', 'symbols', '芒果'],
  ['🥮', 'moon cake', 'symbols', ''],
  ['🥯', 'bagel', 'symbols', '贝果,面包圈'],
  ['🥰', 'smiling face with smiling eyes and three hearts', 'smileys', '爱,微笑,爱心'],
  ['🥱', 'yawning face', 'smileys', '打哈欠,困,无聊'],
  ['🥲', 'smiling face with tear', 'smileys', ''],
  ['🥳', 'face with party horn and party hat', 'smileys', '庆祝,派对,欢呼'],
  ['🥴', 'face with uneven eyes and wavy mouth', 'smileys', '晕,醉,头昏'],
  ['🥵', 'overheated face', 'smileys', '热'],
  ['🥶', 'freezing face', 'smileys', '冷'],
  ['🥷', 'ninja', 'people', '忍者,忍者'],
  ['🥸', 'disguised face', 'symbols', '伪装'],
  ['🥹', 'face holding back tears', 'symbols', '感动,忍住,哭,泪目'],
  ['🥺', 'face with pleading eyes', 'smileys', '可怜,委屈,求'],
  ['🥻', 'sari', 'symbols', '纱丽,印度'],
  ['🥼', 'lab coat', 'symbols', ''],
  ['🥽', 'goggles', 'symbols', ''],
  ['🥾', 'hiking boot', 'symbols', '靴子,登山鞋'],
  ['🥿', 'flat shoe', 'symbols', '平底鞋,鞋'],
  ['🦀', 'crab', 'animals', '螃蟹,海鲜'],
  ['🦁', 'lion face', 'animals', ''],
  ['🦂', 'scorpion', 'animals', ''],
  ['🦃', 'turkey', 'animals', '火鸡,感恩节'],
  ['🦄', 'unicorn face', 'animals', '独角兽,梦幻'],
  ['🦅', 'eagle', 'animals', '老鹰,鹰'],
  ['🦆', 'duck', 'animals', '鸭子,鸭'],
  ['🦇', 'bat', 'animals', '蝙蝠'],
  ['🦈', 'shark', 'animals', '鲨鱼,鱼'],
  ['🦉', 'owl', 'animals', '猫头鹰,智慧'],
  ['🦊', 'fox face', 'animals', ''],
  ['🦋', 'butterfly', 'animals', ''],
  ['🦌', 'deer', 'animals', '鹿,麋鹿'],
  ['🦍', 'gorilla', 'animals', ''],
  ['🦎', 'lizard', 'animals', '蜥蜴,爬行动物'],
  ['🦏', 'rhinoceros', 'animals', '犀牛'],
  ['🦐', 'shrimp', 'animals', '虾,海鲜'],
  ['🦑', 'squid', 'animals', '鱿鱼,海鲜'],
  ['🦒', 'giraffe face', 'animals', '长颈鹿'],
  ['🦓', 'zebra face', 'animals', '斑马'],
  ['🦔', 'hedgehog', 'animals', '刺猬'],
  ['🦕', 'sauropod', 'animals', '恐龙,雷龙'],
  ['🦖', 't-rex', 'animals', '恐龙,霸王龙'],
  ['🦗', 'cricket', 'animals', ''],
  ['🦘', 'kangaroo', 'animals', '袋鼠'],
  ['🦙', 'llama', 'animals', '羊驼,草泥马'],
  ['🦚', 'peacock', 'animals', '孔雀,开屏'],
  ['🦛', 'hippopotamus', 'animals', '河马'],
  ['🦜', 'parrot', 'animals', '鹦鹉'],
  ['🦝', 'raccoon', 'animals', '浣熊'],
  ['🦞', 'lobster', 'animals', '龙虾,海鲜'],
  ['🦟', 'mosquito', 'animals', ''],
  ['🦠', 'microbe', 'animals', ''],
  ['🦡', 'badger', 'animals', '獾'],
  ['🦢', 'swan', 'animals', '天鹅,鹅'],
  ['🦣', 'mammoth', 'animals', '猛犸象'],
  ['🦤', 'dodo', 'animals', '渡渡鸟'],
  ['🦥', 'sloth', 'animals', '树懒'],
  ['🦦', 'otter', 'animals', '水獭'],
  ['🦧', 'orangutan', 'animals', ''],
  ['🦨', 'skunk', 'animals', '臭鼬'],
  ['🦩', 'flamingo', 'animals', '火烈鸟,红鹤'],
  ['🦪', 'oyster', 'animals', '生蚝,牡蛎'],
  ['🦫', 'beaver', 'animals', '河狸,海狸'],
  ['🦬', 'bison', 'animals', '野牛,水牛'],
  ['🦭', 'seal', 'animals', '海豹,海狮'],
  ['🦮', 'guide dog', 'animals', '导盲犬,狗'],
  ['🦯', 'probing cane', 'symbols', ''],
  ['🦰', 'emoji component red hair', 'people', '红发,头发,发色'],
  ['🦱', 'emoji component curly hair', 'people', '卷发,头发'],
  ['🦲', 'emoji component bald', 'people', '光头,秃头'],
  ['🦳', 'emoji component white hair', 'people', '白发,头发'],
  ['🦴', 'bone', 'people', ''],
  ['🦵', 'leg', 'people', '腿,大腿'],
  ['🦶', 'foot', 'people', '脚,足'],
  ['🦷', 'tooth', 'people', '牙齿,牙'],
  ['🦸', 'superhero', 'people', '英雄'],
  ['🦹', 'supervillain', 'people', '超级反派,坏人,反派'],
  ['🦺', 'safety vest', 'symbols', ''],
  ['🦻', 'ear with hearing aid', 'symbols', '助听器,耳朵'],
  ['🦼', 'motorized wheelchair', 'people', ''],
  ['🦽', 'manual wheelchair', 'people', ''],
  ['🦾', 'mechanical arm', 'people', '机械臂,机器人,义肢'],
  ['🦿', 'mechanical leg', 'people', '机械腿,义肢'],
  ['🧀', 'cheese wedge', 'food', '奶酪,芝士'],
  ['🧁', 'cupcake', 'food', '纸杯蛋糕,杯子蛋糕'],
  ['🧂', 'salt shaker', 'food', ''],
  ['🧃', 'beverage box', 'food', '果汁盒,饮料'],
  ['🧄', 'garlic', 'food', '大蒜,蒜'],
  ['🧅', 'onion', 'food', '洋葱'],
  ['🧆', 'falafel', 'food', '鹰嘴豆丸子'],
  ['🧇', 'waffle', 'food', '华夫饼'],
  ['🧈', 'butter', 'food', '黄油,奶油'],
  ['🧉', 'mate drink', 'food', '马黛茶'],
  ['🧊', 'ice cube', 'food', '冰块,冰'],
  ['🧋', 'bubble tea', 'food', '奶茶,珍珠奶茶'],
  ['🧌', 'troll', 'symbols', '巨魔,妖怪'],
  ['🧍', 'standing person', 'symbols', '站立,站着,人'],
  ['🧎', 'kneeling person', 'symbols', '跪,跪下,祈祷'],
  ['🧏', 'deaf person', 'symbols', ''],
  ['🧐', 'face with monocle', 'people', '检查,研究,眼镜'],
  ['🧑', 'adult', 'people', '人'],
  ['🧒', 'child', 'people', ''],
  ['🧓', 'older adult', 'people', '老人,奶奶,爷爷'],
  ['🧔', 'bearded person', 'people', '胡子,胡须,大叔'],
  ['🧕', 'person with headscarf', 'people', '头巾'],
  ['🧖', 'person in steamy room', 'people', '桑拿,蒸汽,洗澡'],
  ['🧗', 'person climbing', 'people', '攀岩'],
  ['🧘', 'person in lotus position', 'people', '打坐'],
  ['🧙', 'mage', 'people', '巫师,魔法师,法师'],
  ['🧚', 'fairy', 'people', '仙女,精灵,小仙女'],
  ['🧛', 'vampire', 'people', '吸血鬼,德古拉'],
  ['🧜', 'merperson', 'people', '美人鱼,人鱼'],
  ['🧝', 'elf', 'people', '精灵,耳朵'],
  ['🧞', 'genie', 'people', '灯神,精灵,神灯'],
  ['🧟', 'zombie', 'people', '僵尸,丧尸'],
  ['🧠', 'brain', 'people', '大脑,思考,记忆,AI'],
  ['🧡', 'orange heart', 'people', ''],
  ['🧢', 'billed cap', 'people', '棒球帽,帽子'],
  ['🧣', 'scarf', 'people', '围巾,冬天'],
  ['🧤', 'gloves', 'people', '手套,冬天'],
  ['🧥', 'coat', 'people', '大衣,外套'],
  ['🧦', 'socks', 'people', '袜子'],
  ['🧧', 'red gift envelope', 'objects', '红包,利是,新年'],
  ['🧨', 'firecracker', 'objects', ''],
  ['🧩', 'jigsaw puzzle piece', 'objects', '拼图,拼图游戏'],
  ['🧪', 'test tube', 'objects', '试管,实验,化学,科学'],
  ['🧫', 'petri dish', 'objects', '培养皿,实验,细菌'],
  ['🧬', 'dna double helix', 'objects', 'DNA,基因,生物'],
  ['🧭', 'compass', 'objects', '指南针'],
  ['🧮', 'abacus', 'objects', '算盘,计算'],
  ['🧯', 'fire extinguisher', 'objects', '灭火器,消防'],
  ['🧰', 'toolbox', 'objects', '工具箱,工具'],
  ['🧱', 'brick', 'objects', '砖'],
  ['🧲', 'magnet', 'objects', '磁铁,磁性'],
  ['🧳', 'luggage', 'objects', '行李箱'],
  ['🧴', 'lotion bottle', 'objects', '乳液,护肤,防晒'],
  ['🧵', 'spool of thread', 'objects', '线,针线,缝纫'],
  ['🧶', 'ball of yarn', 'objects', '毛线,织毛衣'],
  ['🧷', 'safety pin', 'objects', '别针,安全别针'],
  ['🧸', 'teddy bear', 'objects', '泰迪熊,玩具熊'],
  ['🧹', 'broom', 'objects', '扫帚'],
  ['🧺', 'basket', 'objects', '篮子'],
  ['🧻', 'roll of paper', 'objects', '纸巾'],
  ['🧼', 'bar of soap', 'objects', '肥皂,洗手,清洁'],
  ['🧽', 'sponge', 'objects', '海绵,清洁'],
  ['🧾', 'receipt', 'objects', '收据'],
  ['🧿', 'nazar amulet', 'objects', '护身符'],
  ['🩰', 'ballet shoes', 'activity', '芭蕾'],
  ['🩱', 'one-piece swimsuit', 'activity', '泳衣'],
  ['🩲', 'briefs', 'activity', '泳裤'],
  ['🩳', 'shorts', 'activity', '短裤'],
  ['🩴', 'thong sandal', 'activity', '凉拖'],
  ['🩵', 'light blue heart', 'activity', '浅蓝'],
  ['🩶', 'grey heart', 'activity', '灰心'],
  ['🩷', 'pink heart', 'activity', '粉色'],
  ['🩸', 'drop of blood', 'activity', '血'],
  ['🩹', 'adhesive bandage', 'activity', '创可贴'],
  ['🩺', 'stethoscope', 'activity', '听诊器'],
  ['🩻', 'x-ray', 'activity', 'X光'],
  ['🩼', 'crutch', 'activity', '拐杖'],
  ['🪀', 'yo-yo', 'objects', '玩具'],
  ['🪁', 'kite', 'objects', '风筝'],
  ['🪂', 'parachute', 'objects', '跳伞'],
  ['🪃', 'boomerang', 'objects', ''],
  ['🪄', 'magic wand', 'objects', '魔杖,魔法,魔术'],
  ['🪅', 'pinata', 'objects', '皮纳塔'],
  ['🪆', 'nesting dolls', 'objects', ''],
  ['🪇', 'maracas', 'objects', '沙锤'],
  ['🪈', 'flute', 'objects', '笛子'],
  ['🪐', 'ringed planet', 'objects', ''],
  ['🪑', 'chair', 'objects', '椅子'],
  ['🪒', 'razor', 'objects', '剃须刀,剃刀'],
  ['🪓', 'axe', 'objects', '斧头,斧子'],
  ['🪔', 'diya lamp', 'objects', '油灯'],
  ['🪕', 'banjo', 'objects', '班卓琴'],
  ['🪖', 'military helmet', 'objects', '军盔'],
  ['🪗', 'accordion', 'objects', '手风琴'],
  ['🪘', 'long drum', 'objects', '鼓'],
  ['🪙', 'coin', 'objects', '金币'],
  ['🪚', 'carpentry saw', 'objects', '锯子,锯'],
  ['🪛', 'screwdriver', 'objects', '螺丝刀'],
  ['🪜', 'ladder', 'objects', '梯子'],
  ['🪝', 'hook', 'objects', '钩子,挂钩'],
  ['🪞', 'mirror', 'objects', '镜子'],
  ['🪟', 'window', 'objects', '窗户'],
  ['🪠', 'plunger', 'objects', '皮搋子,通马桶'],
  ['🪡', 'sewing needle', 'objects', '针,缝纫,刺绣'],
  ['🪢', 'knot', 'objects', ''],
  ['🪣', 'bucket', 'objects', '水桶,桶'],
  ['🪤', 'mouse trap', 'objects', '捕鼠器'],
  ['🪥', 'toothbrush', 'objects', '牙刷,刷牙'],
  ['🪦', 'headstone', 'objects', '墓碑'],
  ['🪧', 'placard', 'objects', '告示牌'],
  ['🪨', 'rock', 'objects', '石头,岩石'],
  ['🪩', 'mirror ball', 'objects', '迪斯科球'],
  ['🪪', 'identification card', 'objects', '身份证'],
  ['🪫', 'low battery', 'objects', '电池,没电,低电量'],
  ['🪬', 'hamsa', 'objects', '手掌印,护身符'],
  ['🪭', 'folding hand fan', 'objects', ''],
  ['🪮', 'hair pick', 'objects', '梳子'],
  ['🪯', 'khanda', 'objects', ''],
  ['🪰', 'fly', 'objects', '苍蝇,飞虫'],
  ['🪱', 'worm', 'objects', ''],
  ['🪲', 'beetle', 'objects', '甲虫,昆虫'],
  ['🪳', 'cockroach', 'objects', '蟑螂,虫子'],
  ['🪴', 'potted plant', 'objects', '盆栽,植物,绿植'],
  ['🪵', 'wood', 'objects', '木头,柴火,木'],
  ['🪶', 'feather', 'objects', '羽毛,羽毛笔'],
  ['🪷', 'lotus', 'objects', '莲花'],
  ['🪸', 'coral', 'objects', '珊瑚'],
  ['🪹', 'empty nest', 'objects', '鸟巢'],
  ['🪺', 'nest with eggs', 'objects', '鸟巢'],
  ['🪻', 'hyacinth', 'objects', '风信子'],
  ['🪼', 'jellyfish', 'objects', '水母'],
  ['🪽', 'wing', 'objects', '翅膀'],
  ['🪿', 'goose', 'objects', '鹅'],
  ['🫀', 'anatomical heart', 'objects', '心脏,心跳'],
  ['🫁', 'lungs', 'objects', '肺,呼吸'],
  ['🫂', 'people hugging', 'objects', '拥抱,人,朋友'],
  ['🫃', 'pregnant man', 'objects', '孕妇,怀孕'],
  ['🫄', 'pregnant person', 'objects', '孕妇,怀孕'],
  ['🫅', 'person with crown', 'objects', '国王,王子,皇冠'],
  ['🫎', 'moose', 'objects', '驼鹿,麋鹿'],
  ['🫏', 'donkey', 'objects', '驴,动物'],
  ['🫐', 'blueberries', 'food', '蓝莓'],
  ['🫑', 'bell pepper', 'food', '甜椒,彩椒'],
  ['🫒', 'olive', 'food', '橄榄'],
  ['🫓', 'flatbread', 'food', '薄饼,饼'],
  ['🫔', 'tamale', 'food', '玉米粉蒸肉'],
  ['🫕', 'fondue', 'food', '奶酪火锅'],
  ['🫖', 'teapot', 'food', '茶壶,茶'],
  ['🫗', 'pouring liquid', 'food', '倒,倒水,水杯'],
  ['🫘', 'beans', 'food', '豆子,红豆'],
  ['🫙', 'jar', 'food', '罐子,玻璃罐'],
  ['🫚', 'ginger root', 'food', '姜,生姜'],
  ['🫛', 'pea pod', 'food', '豌豆荚,豆'],
  ['🫠', 'melting face', 'smileys', '融化'],
  ['🫡', 'saluting face', 'smileys', '敬礼'],
  ['🫢', 'face with open eyes and hand over mouth', 'smileys', '捂眼'],
  ['🫣', 'face with peeking eye', 'smileys', '偷看'],
  ['🫤', 'face with diagonal mouth', 'smileys', '撇嘴'],
  ['🫥', 'dotted line face', 'smileys', '隐形'],
  ['🫦', 'biting lip', 'smileys', '咬唇,嘴唇'],
  ['🫧', 'bubbles', 'smileys', '泡泡'],
  ['🫨', 'shaking face', 'smileys', '摇晃,震动,抖'],
  ['🫰', 'hand with index finger and thumb crossed', 'people', '比心,手指,捏'],
  ['🫱', 'rightwards hand', 'people', '手,右边,推'],
  ['🫲', 'leftwards hand', 'people', '手,左边,推'],
  ['🫳', 'palm down hand', 'people', '手,向下,放'],
  ['🫴', 'palm up hand', 'people', '手,向上,举'],
  ['🫵', 'index pointing at the viewer', 'people', '指,你'],
  ['🫶', 'heart hands', 'people', '比心,爱心,手势'],
  ['🫷', 'leftwards pushing hand', 'people', '手,推,右边'],
  ['🫸', 'rightwards pushing hand', 'people', '手,推,左边'],
  ['‼', 'double exclamation mark', 'symbols', ''],
  ['‼️', 'double exclamation mark', 'symbols', ''],
  ['⁉', 'exclamation question mark', 'symbols', ''],
  ['⁉️', 'exclamation question mark', 'symbols', ''],
  ['™', 'trade mark sign', 'symbols', ''],
  ['™️', 'trade mark sign', 'symbols', ''],
  ['ℹ', 'information source', 'symbols', ''],
  ['ℹ️', 'information source', 'symbols', ''],
  ['↔', 'left right arrow', 'symbols', ''],
  ['↔️', 'left right arrow', 'symbols', ''],
  ['↕', 'up down arrow', 'symbols', ''],
  ['↕️', 'up down arrow', 'symbols', ''],
  ['↖', 'north west arrow', 'symbols', ''],
  ['↖️', 'north west arrow', 'symbols', ''],
  ['↗', 'north east arrow', 'symbols', ''],
  ['↗️', 'north east arrow', 'symbols', ''],
  ['↘', 'south east arrow', 'symbols', ''],
  ['↘️', 'south east arrow', 'symbols', ''],
  ['↙', 'south west arrow', 'symbols', ''],
  ['↙️', 'south west arrow', 'symbols', ''],
  ['↩', 'leftwards arrow with hook', 'symbols', ''],
  ['↩️', 'leftwards arrow with hook', 'symbols', ''],
  ['↪', 'rightwards arrow with hook', 'symbols', ''],
  ['↪️', 'rightwards arrow with hook', 'symbols', ''],
  ['⌚', 'watch', 'objects', '手表'],
  ['⌚️', 'watch', 'objects', ''],
  ['⌛', 'hourglass', 'objects', '沙漏,时间,等待'],
  ['⌛️', 'hourglass', 'objects', ''],
  ['⌨', 'keyboard', 'symbols', ''],
  ['⌨️', 'keyboard', 'symbols', '键盘,打字'],
  ['⏏', 'eject symbol', 'symbols', ''],
  ['⏏️', 'eject symbol', 'symbols', ''],
  ['⏩', 'black right-pointing double triangle', 'objects', ''],
  ['⏪', 'black left-pointing double triangle', 'objects', ''],
  ['⏫', 'black up-pointing double triangle', 'objects', ''],
  ['⏬', 'black down-pointing double triangle', 'objects', ''],
  ['⏭', 'black right-pointing double triangle with vertical bar', 'objects', ''],
  ['⏭️', 'black right-pointing double triangle with vertical bar', 'objects', ''],
  ['⏮', 'black left-pointing double triangle with vertical bar', 'objects', ''],
  ['⏮️', 'black left-pointing double triangle with vertical bar', 'objects', ''],
  ['⏯', 'black right-pointing triangle with double vertical bar', 'objects', ''],
  ['⏯️', 'black right-pointing triangle with double vertical bar', 'objects', ''],
  ['⏰', 'alarm clock', 'objects', '闹钟,时间,起床'],
  ['⏱', 'stopwatch', 'objects', ''],
  ['⏱️', 'stopwatch', 'objects', '秒表'],
  ['⏲', 'timer clock', 'objects', ''],
  ['⏲️', 'timer clock', 'objects', '计时器'],
  ['⏳', 'hourglass with flowing sand', 'objects', '沙漏'],
  ['⏸', 'double vertical bar', 'symbols', ''],
  ['⏸️', 'double vertical bar', 'symbols', ''],
  ['⏹', 'black square for stop', 'symbols', ''],
  ['⏹️', 'black square for stop', 'symbols', ''],
  ['⏺', 'black circle for record', 'symbols', ''],
  ['⏺️', 'black circle for record', 'symbols', ''],
  ['Ⓜ', 'circled latin capital letter m', 'symbols', ''],
  ['Ⓜ️', 'circled latin capital letter m', 'symbols', ''],
  ['▪', 'black small square', 'symbols', ''],
  ['▪️', 'black small square', 'symbols', ''],
  ['▫', 'white small square', 'symbols', ''],
  ['▫️', 'white small square', 'symbols', ''],
  ['▶', 'black right-pointing triangle', 'symbols', ''],
  ['▶️', 'black right-pointing triangle', 'symbols', ''],
  ['◀', 'black left-pointing triangle', 'symbols', ''],
  ['◀️', 'black left-pointing triangle', 'symbols', ''],
  ['◻', 'white medium square', 'symbols', ''],
  ['◻️', 'white medium square', 'symbols', ''],
  ['◼', 'black medium square', 'symbols', ''],
  ['◼️', 'black medium square', 'symbols', ''],
  ['◽', 'white medium small square', 'symbols', ''],
  ['◾', 'black medium small square', 'symbols', ''],
  ['◾️', 'black medium small square', 'symbols', ''],
  ['☀', 'black sun with rays', 'symbols', ''],
  ['☀️', 'black sun with rays', 'symbols', '太阳,晴天,阳光'],
  ['☁', 'cloud', 'symbols', ''],
  ['☁️', 'cloud', 'symbols', '云,多云,天气'],
  ['☂', 'umbrella', 'symbols', ''],
  ['☂️', 'umbrella', 'symbols', ''],
  ['☃', 'snowman', 'symbols', ''],
  ['☃️', 'snowman', 'symbols', '雪人,冬天,雪'],
  ['☄', 'comet', 'symbols', ''],
  ['☄️', 'comet', 'symbols', ''],
  ['☎', 'black telephone', 'symbols', ''],
  ['☎️', 'black telephone', 'symbols', '电话'],
  ['☑', 'ballot box with check', 'symbols', ''],
  ['☑️', 'ballot box with check', 'symbols', ''],
  ['☔', 'umbrella with rain drops', 'symbols', ''],
  ['☔️', 'umbrella with rain drops', 'symbols', ''],
  ['☕', 'hot beverage', 'food', '咖啡,热饮'],
  ['☕️', 'hot beverage', 'food', ''],
  ['☘', 'shamrock', 'symbols', ''],
  ['☘️', 'shamrock', 'symbols', ''],
  ['☝', 'white up pointing index', 'symbols', ''],
  ['☝️', 'white up pointing index', 'symbols', '指,上面,向上'],
  ['☠', 'skull and crossbones', 'symbols', ''],
  ['☠️', 'skull and crossbones', 'symbols', '骷髅,死亡,危险'],
  ['☢', 'radioactive sign', 'symbols', ''],
  ['☢️', 'radioactive sign', 'symbols', ''],
  ['☣', 'biohazard sign', 'symbols', ''],
  ['☣️', 'biohazard sign', 'symbols', ''],
  ['☦', 'orthodox cross', 'symbols', ''],
  ['☦️', 'orthodox cross', 'symbols', ''],
  ['☪', 'star and crescent', 'symbols', ''],
  ['☪️', 'star and crescent', 'symbols', ''],
  ['☮', 'peace symbol', 'symbols', ''],
  ['☮️', 'peace symbol', 'symbols', ''],
  ['☯', 'yin yang', 'symbols', ''],
  ['☯️', 'yin yang', 'symbols', ''],
  ['☸', 'wheel of dharma', 'symbols', ''],
  ['☸️', 'wheel of dharma', 'symbols', ''],
  ['☹', 'white frowning face', 'smileys', ''],
  ['☹️', 'white frowning face', 'smileys', ''],
  ['☺', 'white smiling face', 'smileys', ''],
  ['☺️', 'white smiling face', 'smileys', ''],
  ['♀', 'female sign', 'symbols', ''],
  ['♀️', 'female sign', 'symbols', ''],
  ['♂', 'male sign', 'symbols', ''],
  ['♂️', 'male sign', 'symbols', ''],
  ['♈', 'aries', 'symbols', ''],
  ['♈️', 'aries', 'symbols', ''],
  ['♉', 'taurus', 'symbols', ''],
  ['♉️', 'taurus', 'symbols', ''],
  ['♊', 'gemini', 'symbols', ''],
  ['♊️', 'gemini', 'symbols', ''],
  ['♋', 'cancer', 'symbols', ''],
  ['♋️', 'cancer', 'symbols', ''],
  ['♌', 'leo', 'symbols', ''],
  ['♌️', 'leo', 'symbols', ''],
  ['♍', 'virgo', 'symbols', ''],
  ['♍️', 'virgo', 'symbols', ''],
  ['♎', 'libra', 'symbols', ''],
  ['♎️', 'libra', 'symbols', ''],
  ['♏', 'scorpius', 'symbols', ''],
  ['♏️', 'scorpius', 'symbols', ''],
  ['♐', 'sagittarius', 'symbols', ''],
  ['♐️', 'sagittarius', 'symbols', ''],
  ['♑', 'capricorn', 'symbols', ''],
  ['♑️', 'capricorn', 'symbols', ''],
  ['♒', 'aquarius', 'symbols', ''],
  ['♒️', 'aquarius', 'symbols', ''],
  ['♓', 'pisces', 'symbols', ''],
  ['♓️', 'pisces', 'symbols', ''],
  ['♟', 'black chess pawn', 'symbols', ''],
  ['♟️', 'black chess pawn', 'symbols', '棋子,国际象棋,象棋'],
  ['♠', 'black spade suit', 'symbols', ''],
  ['♠️', 'black spade suit', 'symbols', ''],
  ['♣', 'black club suit', 'symbols', ''],
  ['♣️', 'black club suit', 'symbols', ''],
  ['♥', 'black heart suit', 'symbols', ''],
  ['♥️', 'black heart suit', 'symbols', ''],
  ['♦', 'black diamond suit', 'symbols', ''],
  ['♦️', 'black diamond suit', 'symbols', ''],
  ['♨', 'hot springs', 'symbols', ''],
  ['♨️', 'hot springs', 'symbols', '温泉,热泉'],
  ['♻', 'black universal recycling symbol', 'symbols', ''],
  ['♻️', 'black universal recycling symbol', 'symbols', ''],
  ['♾', 'permanent paper sign', 'symbols', ''],
  ['♾️', 'permanent paper sign', 'symbols', ''],
  ['♿', 'wheelchair symbol', 'symbols', ''],
  ['♿️', 'wheelchair symbol', 'symbols', ''],
  ['⚒', 'hammer and pick', 'symbols', ''],
  ['⚒️', 'hammer and pick', 'symbols', '锤子,工具'],
  ['⚓', 'anchor', 'symbols', '锚,航海,停泊'],
  ['⚔', 'crossed swords', 'symbols', ''],
  ['⚔️', 'crossed swords', 'symbols', '剑,交叉,战斗'],
  ['⚕', 'staff of aesculapius', 'symbols', ''],
  ['⚕️', 'staff of aesculapius', 'symbols', ''],
  ['⚖', 'scales', 'symbols', ''],
  ['⚖️', 'scales', 'symbols', ''],
  ['⚗', 'alembic', 'symbols', ''],
  ['⚗️', 'alembic', 'symbols', ''],
  ['⚙', 'gear', 'symbols', ''],
  ['⚙️', 'gear', 'symbols', ''],
  ['⚛', 'atom symbol', 'symbols', ''],
  ['⚛️', 'atom symbol', 'symbols', ''],
  ['⚜', 'fleur-de-lis', 'symbols', ''],
  ['⚜️', 'fleur-de-lis', 'symbols', ''],
  ['⚠', 'warning sign', 'symbols', ''],
  ['⚠️', 'warning sign', 'symbols', ''],
  ['⚡', 'high voltage sign', 'symbols', ''],
  ['⚧', 'male with stroke and male and female sign', 'symbols', ''],
  ['⚧️', 'male with stroke and male and female sign', 'symbols', ''],
  ['⚪', 'medium white circle', 'symbols', ''],
  ['⚪️', 'medium white circle', 'symbols', ''],
  ['⚫', 'medium black circle', 'symbols', ''],
  ['⚰', 'coffin', 'symbols', ''],
  ['⚰️', 'coffin', 'symbols', '棺材,死亡'],
  ['⚱', 'funeral urn', 'symbols', ''],
  ['⚱️', 'funeral urn', 'symbols', '骨灰盒,死亡'],
  ['⚽', 'soccer ball', 'activity', '足球,球'],
  ['⚽️', 'soccer ball', 'activity', ''],
  ['⚾', 'baseball', 'activity', '棒球,球'],
  ['⚾️', 'baseball', 'activity', ''],
  ['⛄', 'snowman without snow', 'symbols', '雪人,冬天'],
  ['⛄️', 'snowman without snow', 'symbols', ''],
  ['⛅', 'sun behind cloud', 'symbols', '太阳,云,多云'],
  ['⛈', 'thunder cloud and rain', 'symbols', ''],
  ['⛈️', 'thunder cloud and rain', 'symbols', '雷雨,雷暴,天气'],
  ['⛎', 'ophiuchus', 'symbols', ''],
  ['⛏', 'pick', 'symbols', ''],
  ['⛏️', 'pick', 'symbols', '镐,工具'],
  ['⛑', 'helmet with white cross', 'symbols', ''],
  ['⛑️', 'helmet with white cross', 'symbols', '头盔,救援,安全'],
  ['⛓', 'chains', 'symbols', ''],
  ['⛓️', 'chains', 'symbols', ''],
  ['⛔', 'no entry', 'symbols', ''],
  ['⛩', 'shinto shrine', 'travel', ''],
  ['⛩️', 'shinto shrine', 'travel', '鸟居,神社,日本'],
  ['⛪', 'church', 'travel', '教堂'],
  ['⛰', 'mountain', 'travel', ''],
  ['⛰️', 'mountain', 'travel', '山,山峰'],
  ['⛱', 'umbrella on ground', 'travel', ''],
  ['⛱️', 'umbrella on ground', 'travel', ''],
  ['⛲', 'fountain', 'travel', '喷泉'],
  ['⛲️', 'fountain', 'travel', ''],
  ['⛳', 'flag in hole', 'activity', '高尔夫,高尔夫球,球洞'],
  ['⛳️', 'flag in hole', 'activity', ''],
  ['⛴', 'ferry', 'travel', ''],
  ['⛴️', 'ferry', 'travel', '渡轮,船'],
  ['⛵', 'sailboat', 'travel', '帆船,船'],
  ['⛵️', 'sailboat', 'travel', ''],
  ['⛷', 'skier', 'activity', ''],
  ['⛷️', 'skier', 'activity', ''],
  ['⛸', 'ice skate', 'activity', ''],
  ['⛸️', 'ice skate', 'activity', '溜冰,冰刀,滑冰'],
  ['⛹', 'person with ball', 'activity', ''],
  ['⛹️', 'person with ball', 'activity', ''],
  ['⛺', 'tent', 'travel', '帐篷,露营'],
  ['⛺️', 'tent', 'travel', ''],
  ['⛽', 'fuel pump', 'travel', '加油站,加油,汽油'],
  ['✂', 'black scissors', 'symbols', ''],
  ['✂️', 'black scissors', 'symbols', ''],
  ['✅', 'white heavy check mark', 'symbols', ''],
  ['✈', 'airplane', 'travel', ''],
  ['✈️', 'airplane', 'travel', '飞机,航班,起飞'],
  ['✉', 'envelope', 'symbols', ''],
  ['✉️', 'envelope', 'symbols', '信封,邮件,信'],
  ['✊', 'raised fist', 'people', '拳头,加油,力量'],
  ['✋', 'raised hand', 'people', '手,举手,停'],
  ['✌', 'victory hand', 'symbols', ''],
  ['✌️', 'victory hand', 'symbols', '胜利,耶,剪刀手'],
  ['✍', 'writing hand', 'symbols', ''],
  ['✍️', 'writing hand', 'symbols', '写字,写作,手'],
  ['✏', 'pencil', 'symbols', ''],
  ['✏️', 'pencil', 'symbols', ''],
  ['✒', 'black nib', 'symbols', ''],
  ['✒️', 'black nib', 'symbols', ''],
  ['✔', 'heavy check mark', 'symbols', ''],
  ['✔️', 'heavy check mark', 'symbols', ''],
  ['✖', 'heavy multiplication x', 'symbols', ''],
  ['✖️', 'heavy multiplication x', 'symbols', ''],
  ['✝', 'latin cross', 'symbols', ''],
  ['✝️', 'latin cross', 'symbols', ''],
  ['✡', 'star of david', 'symbols', ''],
  ['✡️', 'star of david', 'symbols', ''],
  ['✨', 'sparkles', 'symbols', '星星,闪光,发光'],
  ['✳', 'eight spoked asterisk', 'symbols', ''],
  ['✳️', 'eight spoked asterisk', 'symbols', ''],
  ['✴', 'eight pointed black star', 'symbols', ''],
  ['✴️', 'eight pointed black star', 'symbols', ''],
  ['❄', 'snowflake', 'symbols', ''],
  ['❄️', 'snowflake', 'symbols', '雪花,雪,冬天,冷'],
  ['❇', 'sparkle', 'symbols', ''],
  ['❇️', 'sparkle', 'symbols', ''],
  ['❌', 'cross mark', 'symbols', ''],
  ['❎', 'negative squared cross mark', 'symbols', ''],
  ['❓', 'black question mark ornament', 'symbols', ''],
  ['❔', 'white question mark ornament', 'symbols', ''],
  ['❕', 'white exclamation mark ornament', 'symbols', ''],
  ['❗', 'heavy exclamation mark symbol', 'symbols', ''],
  ['❗️', 'heavy exclamation mark symbol', 'symbols', ''],
  ['❣', 'heavy heart exclamation mark ornament', 'symbols', ''],
  ['❣️', 'heavy heart exclamation mark ornament', 'symbols', '爱心,感叹号'],
  ['❤', 'heavy black heart', 'smileys', ''],
  ['❤️', 'heavy black heart', 'smileys', '爱心,红心,爱'],
  ['➕', 'heavy plus sign', 'symbols', ''],
  ['➖', 'heavy minus sign', 'symbols', ''],
  ['➗', 'heavy division sign', 'symbols', ''],
  ['➡', 'black rightwards arrow', 'symbols', ''],
  ['➡️', 'black rightwards arrow', 'symbols', ''],
  ['➰', 'curly loop', 'symbols', ''],
  ['➿', 'double curly loop', 'symbols', ''],
  ['⬅', 'leftwards black arrow', 'symbols', ''],
  ['⬅️', 'leftwards black arrow', 'symbols', ''],
  ['⬆', 'upwards black arrow', 'symbols', ''],
  ['⬆️', 'upwards black arrow', 'symbols', ''],
  ['⬇', 'downwards black arrow', 'symbols', ''],
  ['⬇️', 'downwards black arrow', 'symbols', ''],
  ['⬛', 'black large square', 'symbols', ''],
  ['⬛️', 'black large square', 'symbols', ''],
  ['⬜', 'white large square', 'symbols', ''],
  ['⬜️', 'white large square', 'symbols', ''],
  ['⭐', 'white medium star', 'symbols', '星星,五星,评分'],
  ['⭕', 'heavy large circle', 'symbols', ''],
  ['⭕️', 'heavy large circle', 'symbols', ''],
  ['⤴', 'arrow pointing rightwards then curving upwards', 'symbols', ''],
  ['⤴️', 'arrow pointing rightwards then curving upwards', 'symbols', ''],
  ['⤵', 'arrow pointing rightwards then curving downwards', 'symbols', ''],
  ['⤵️', 'arrow pointing rightwards then curving downwards', 'symbols', ''],
  ['〰', 'wavy dash', 'symbols', ''],
  ['〰️', 'wavy dash', 'symbols', ''],
  ['〽', 'part alternation mark', 'symbols', ''],
  ['〽️', 'part alternation mark', 'symbols', ''],
  ['㊗', 'circled ideograph congratulation', 'symbols', ''],
  ['㊗️', 'circled ideograph congratulation', 'symbols', ''],
  ['㊙', 'circled ideograph secret', 'symbols', ''],
  ['㊙️', 'circled ideograph secret', 'symbols', ''],
  ['©', 'copyright sign', 'symbols', ''],
  ['©️', 'copyright sign', 'symbols', ''],
  ['®', 'registered sign', 'symbols', ''],
  ['®️', 'registered sign', 'symbols', ''],
  ['👨‍💻', 'man technologist', 'people', '程序员,开发者,工程师,码农'],
  ['👩‍💻', 'woman technologist', 'people', '程序员,开发者,工程师'],
  ['🧑‍💻', 'technologist', 'people', '程序员,开发者,工程师'],
  ['👨‍🔧', 'man mechanic', 'people', ''],
  ['👩‍🔧', 'woman mechanic', 'people', ''],
  ['👨‍🎨', 'man artist', 'people', ''],
  ['👩‍🎨', 'woman artist', 'people', ''],
  ['👨‍🚀', 'man astronaut', 'people', ''],
  ['👩‍🚀', 'woman astronaut', 'people', ''],
  ['👨‍⚕️', 'man health worker', 'people', ''],
  ['👩‍⚕️', 'woman health worker', 'people', ''],
  ['👨‍🏫', 'man teacher', 'people', ''],
  ['👩‍🏫', 'woman teacher', 'people', ''],
  ['👨‍🍳', 'man cook', 'people', ''],
  ['👩‍🍳', 'woman cook', 'people', ''],
  ['👨‍🌾', 'man farmer', 'people', ''],
  ['👩‍🌾', 'woman farmer', 'people', ''],
  ['👩‍🏭', 'woman factory worker', 'people', ''],
  ['👨‍🎓', 'man student', 'people', ''],
  ['👩‍🎓', 'woman student', 'people', ''],
  ['👨‍🚒', 'man firefighter', 'people', ''],
  ['👩‍🚒', 'woman firefighter', 'people', ''],
  ['👨‍⚖️', 'man judge', 'people', ''],
  ['👩‍⚖️', 'woman judge', 'people', ''],
  ['👨‍💼', 'man office worker', 'people', ''],
  ['👩‍💼', 'woman office worker', 'people', ''],
  ['👨‍🎤', 'man singer', 'people', ''],
  ['👩‍🎤', 'woman singer', 'people', ''],
  ['👨‍🦰', 'man red hair', 'people', ''],
  ['👩‍🦰', 'woman red hair', 'people', ''],
  ['👨‍🦱', 'man curly hair', 'people', ''],
  ['👩‍🦱', 'woman curly hair', 'people', ''],
  ['👩‍🦲', 'woman bald', 'people', ''],
  ['👨‍🦳', 'man white hair', 'people', ''],
  ['👩‍🦳', 'woman white hair', 'people', ''],
  ['👩‍❤️‍👨', 'couple with heart', 'people', ''],
  ['👨‍❤️‍👨', 'couple with heart', 'people', ''],
  ['👩‍❤️‍👩', 'couple with heart', 'people', ''],
  ['👨‍👩‍👧', 'family man woman girl', 'people', ''],
  ['👨‍👩‍👦', 'family man woman boy', 'people', ''],
  ['👨‍👩‍👧‍👦', 'family man woman girl boy', 'people', ''],
  ['👨‍👩‍👦‍👦', 'man', 'people', ''],
  ['👨‍👩‍👧‍👧', 'family man woman girl girl', 'people', ''],
  ['👩‍👩‍👧', 'family woman woman girl', 'people', ''],
  ['👨‍👨‍👧', 'family man man girl', 'people', ''],
  ['👨‍👦', 'family man boy', 'people', ''],
  ['👩‍👧', 'family woman girl', 'people', ''],
  ['👨‍👧‍👦', 'family man girl boy', 'people', ''],
  ['👩‍❤️‍💋‍👨', 'kiss woman man', 'people', ''],
  ['🧑‍🤝‍🧑', 'people holding hands', 'people', ''],
  ['❤️‍🔥', 'heart on fire', 'smileys', ''],
  ['🧑‍🚒', 'firefighter', 'people', '消防员'],
  ['🧑‍🏭', 'factory worker', 'people', ''],
  ['🧑‍🎓', 'student', 'people', '学生,毕业生,大学生'],
  ['🧑‍🏫', 'teacher', 'people', '老师,教师,教授'],
  ['🧑‍🎤', 'singer', 'people', '歌手,歌星'],
  ['🧑‍⚕️', 'health worker', 'people', '医生,医疗'],
  ['🧑‍⚖️', 'judge', 'people', '法官,审判'],
  ['🧑‍🍳', 'cook', 'people', '厨师,大厨'],
  ['🧑‍🌾', 'farmer', 'people', '农民,农夫'],
  ['🧑‍🎨', 'artist', 'people', '画家,艺术家'],
  ['🧑‍🔬', 'scientist', 'people', ''],
  ['🧑‍🔧', 'mechanic', 'people', '技工,维修工'],
  ['🧑‍💼', 'office worker', 'people', '白领,上班族,职员'],
  ['🧑‍🚀', 'astronaut', 'people', '宇航员,太空人'],
  ['🏃‍♂️', 'man running', 'activity', ''],
  ['🏃‍♀️', 'woman running', 'activity', ''],
  ['🚶‍♂️', 'man walking', 'travel', ''],
  ['🚶‍♀️', 'woman walking', 'travel', ''],
  ['🧎‍♂️', 'man kneeling', 'symbols', ''],
  ['🧎‍♀️', 'woman kneeling', 'symbols', ''],
  ['🏋️‍♂️', 'man lifting weights', 'activity', ''],
  ['🏋️‍♀️', 'woman lifting weights', 'activity', ''],
  ['🤸‍♂️', 'man cartwheeling', 'people', ''],
  ['🤸‍♀️', 'woman cartwheeling', 'people', ''],
  ['⛹️‍♂️', 'man bouncing ball', 'activity', ''],
  ['⛹️‍♀️', 'woman bouncing ball', 'activity', ''],
  ['🤾‍♂️', 'man playing handball', 'activity', ''],
  ['🤾‍♀️', 'woman playing handball', 'activity', ''],
  ['🧘‍♀️', 'woman in lotus position', 'people', ''],
  ['🏄‍♂️', 'man surfing', 'activity', ''],
  ['🏄‍♀️', 'woman surfing', 'activity', ''],
  ['🏊‍♂️', 'man swimming', 'activity', ''],
  ['🏊‍♀️', 'woman swimming', 'activity', ''],
  ['🚴‍♂️', 'man biking', 'travel', ''],
  ['🚴‍♀️', 'woman biking', 'travel', ''],
  ['🚵‍♂️', 'man mountain biking', 'travel', ''],
  ['🚵‍♀️', 'woman mountain biking', 'travel', ''],
  ['👯‍♂️', 'men with bunny ears', 'people', ''],
  ['👯‍♀️', 'women with bunny ears', 'people', ''],
  ['🧖‍♂️', 'man in steamy room', 'people', ''],
  ['🧖‍♀️', 'woman in steamy room', 'people', ''],
  ['🧗‍♂️', 'man climbing', 'people', ''],
  ['🧗‍♀️', 'woman climbing', 'people', ''],
  ['🤦‍♂️', 'man facepalming', 'smileys', ''],
  ['🤦‍♀️', 'woman facepalming', 'smileys', ''],
  ['🤷‍♂️', 'man shrugging', 'people', ''],
  ['🤷‍♀️', 'woman shrugging', 'people', ''],
  ['🙍‍♂️', 'person frowning', 'smileys', ''],
  ['🙍‍♀️', 'woman frowning', 'smileys', ''],
  ['🙎‍♂️', 'man pouting', 'smileys', ''],
  ['🙎‍♀️', 'woman pouting', 'smileys', ''],
  ['🙅‍♂️', 'man gesturing no', 'smileys', ''],
  ['🙅‍♀️', 'woman gesturing no', 'smileys', ''],
  ['🙆‍♂️', 'man gesturing ok', 'smileys', ''],
  ['🙆‍♀️', 'woman gesturing ok', 'smileys', ''],
  ['💁‍♂️', 'man tipping hand', 'people', ''],
  ['💁‍♀️', 'woman tipping hand', 'people', ''],
  ['🙋‍♂️', 'man raising hand', 'smileys', ''],
  ['🙋‍♀️', 'woman raising hand', 'smileys', ''],
  ['🙇‍♂️', 'man bowing', 'smileys', ''],
  ['🙇‍♀️', 'woman bowing', 'smileys', ''],
  ['💆‍♂️', 'man getting massage', 'people', ''],
  ['💆‍♀️', 'woman getting massage', 'people', ''],
  ['💇‍♂️', 'man getting haircut', 'people', ''],
  ['💇‍♀️', 'woman getting haircut', 'people', ''],
  ['🧞‍♂️', 'man genie', 'people', ''],
  ['🧞‍♀️', 'woman genie', 'people', ''],
  ['🧟‍♂️', 'man zombie', 'people', ''],
  ['🧟‍♀️', 'woman zombie', 'people', ''],
  ['🧜‍♂️', 'merman', 'people', ''],
  ['🧚‍♂️', 'man fairy', 'people', ''],
  ['🧚‍♀️', 'woman fairy', 'people', ''],
  ['🧛‍♂️', 'man vampire', 'people', ''],
  ['🧛‍♀️', 'woman vampire', 'people', ''],
  ['🧙‍♂️', 'man mage', 'people', ''],
  ['🧙‍♀️', 'mage', 'people', ''],
  ['🧝‍♂️', 'man elf', 'people', ''],
  ['🧝‍♀️', 'woman elf', 'people', ''],
  ['🦸‍♂️', 'man superhero', 'people', ''],
  ['🦸‍♀️', 'woman superhero', 'people', ''],
  ['🦹‍♂️', 'man supervillain', 'people', ''],
  ['🦹‍♀️', 'woman supervillain', 'people', ''],
  ['0️⃣', 'keycap 0', 'symbols', ''],
  ['1️⃣', 'keycap 1', 'symbols', ''],
  ['2️⃣', 'keycap 2', 'symbols', ''],
  ['3️⃣', 'keycap 3', 'symbols', ''],
  ['4️⃣', 'keycap 4', 'symbols', ''],
  ['5️⃣', 'keycap 5', 'symbols', ''],
  ['6️⃣', 'keycap 6', 'symbols', ''],
  ['7️⃣', 'keycap 7', 'symbols', ''],
  ['8️⃣', 'keycap 8', 'symbols', ''],
  ['9️⃣', 'keycap 9', 'symbols', ''],
  ['#️⃣', 'keycap #', 'symbols', ''],
  ['*️⃣', 'keycap *', 'symbols', ''],
  ['🇨🇳', 'flag china', 'flags', '中国,国旗,五星红旗'],
  ['🇺🇸', 'flag united states', 'flags', '美国,国旗,USA'],
  ['🇬🇧', 'flag united kingdom', 'flags', '英国,国旗,UK'],
  ['🇯🇵', 'flag japan', 'flags', '日本,国旗'],
  ['🇫🇷', 'flag france', 'flags', '法国,国旗'],
  ['🇩🇪', 'flag germany', 'flags', '德国,国旗'],
  ['🇮🇹', 'flag italy', 'flags', '意大利,国旗'],
  ['🇪🇸', 'flag spain', 'flags', '西班牙,国旗'],
  ['🇷🇺', 'flag russia', 'flags', '俄罗斯,国旗'],
  ['🇮🇳', 'regional indicator symbol letter i', 'flags', '印度,国旗'],
  ['🇧🇷', 'flag brazil', 'flags', '巴西,国旗'],
  ['🇨🇦', 'flag canada', 'flags', '加拿大,国旗'],
  ['🇦🇺', 'flag australia', 'flags', '澳大利亚,国旗'],
  ['🇸🇬', 'flag singapore', 'flags', '新加坡,国旗'],
  ['🇭🇰', 'flag hong kong', 'flags', '香港,国旗,区旗'],
  ['🇹🇼', 'flag taiwan', 'flags', '台湾,国旗'],
  ['🇲🇴', 'flag macau', 'flags', '澳门,国旗'],
  ['🇻🇳', 'flag vietnam', 'flags', '越南,国旗'],
  ['🇲🇾', 'regional indicator symbol letter m', 'flags', '马来西亚,国旗'],
  ['🇮🇩', 'flag indonesia', 'flags', '印尼,国旗'],
  ['🇵🇭', 'flag philippines', 'flags', '菲律宾,国旗'],
  ['🇹🇷', 'flag turkey', 'flags', '土耳其,国旗'],
  ['🇸🇦', 'flag saudi arabia', 'flags', '沙特,国旗'],
  ['🇦🇪', 'flag united arab emirates', 'flags', '阿联酋,国旗'],
  ['🇳🇱', 'flag netherlands', 'flags', '荷兰,国旗'],
  ['🇸🇪', 'flag sweden', 'flags', '瑞典,国旗'],
  ['🇨🇭', 'flag switzerland', 'flags', '瑞士,国旗'],
  ['🇦🇹', 'flag austria', 'flags', '奥地利,国旗'],
  ['🇧🇪', 'flag belgium', 'flags', '比利时,国旗'],
  ['🇵🇹', 'flag portugal', 'flags', '葡萄牙,国旗'],
  ['🇬🇷', 'flag greece', 'flags', '希腊,国旗'],
  ['🇳🇴', 'flag norway', 'flags', '挪威,国旗'],
  ['🇩🇰', 'flag denmark', 'flags', '丹麦,国旗'],
  ['🇫🇮', 'flag finland', 'flags', '芬兰,国旗'],
  ['🇵🇱', 'flag poland', 'flags', '波兰,国旗'],
  ['🇺🇦', 'flag ukraine', 'flags', '乌克兰,国旗'],
  ['🇮🇱', 'flag israel', 'flags', '以色列,国旗'],
  ['🇪🇬', 'flag egypt', 'flags', '埃及,国旗'],
  ['🇿🇦', 'flag south africa', 'flags', '南非,国旗'],
  ['🇳🇬', 'flag nigeria', 'flags', '尼日利亚,国旗'],
  ['🇲🇽', 'flag mexico', 'flags', '墨西哥,国旗'],
  ['🇦🇷', 'flag argentina', 'flags', ''],
  ['🇨🇱', 'flag chile', 'flags', '智利,国旗'],
  ['🇰🇿', 'flag kazakhstan', 'flags', '哈萨克斯坦,国旗'],
  ['🇺🇿', 'flag uzbekistan', 'flags', '乌兹别克斯坦,国旗'],
  ['🇳🇿', 'flag new zealand', 'flags', '新西兰,国旗'],
  ['🇮🇪', 'flag ireland', 'flags', '爱尔兰,国旗'],
  ['🇨🇿', 'flag czechia', 'flags', '捷克,国旗'],
  ['👍🏻', 'thumbs up light skin', 'people', ''],
  ['👍🏽', 'thumbs up sign', 'people', ''],
  ['👍🏾', 'thumbs up medium dark skin', 'people', ''],
  ['👍🏿', 'thumbs up dark skin', 'people', ''],
  ['👏🏻', 'clapping hands light skin', 'people', ''],
  ['👏🏼', 'clapping hands medium light skin', 'people', ''],
  ['👏🏽', 'clapping hands medium skin', 'people', ''],
  ['👏🏾', 'clapping hands medium dark skin', 'people', ''],
  ['👏🏿', 'clapping hands dark skin', 'people', ''],
  ['🙏🏻', 'folded hands light skin', 'smileys', ''],
  ['🙏🏼', 'folded hands medium light skin', 'smileys', ''],
  ['🙏🏽', 'folded hands medium skin', 'smileys', ''],
  ['🙏🏾', 'folded hands medium dark skin', 'smileys', ''],
  ['🙏🏿', 'folded hands dark skin', 'smileys', ''],
  ['🏳️‍🌈', 'rainbow flag', 'flags', ''],
  ['🏴‍☠️', 'pirate flag', 'flags', '海盗旗,海盗'],
];
